### ISSUE TITLE
Autocomplete. I don't have any. 

### ISSUE THREAD

**Issue by seanparkross** [eza-community/eza#1015]
How can I get autocomplete for Eza?

I'm bouncing between normal mac terminal with Amazon Q and Warp and neither give me any autocomplete.

**Comment by MartinFillon** [comment]
Hello, could you tell me what shell you are using inside your terminals ? In order for me to guide you on how to autocomplete eza.

**Comment by seanparkross** [comment]
Hi there. It's zsh. 🙏

**Comment by MartinFillon** [comment]
Please see [this](https://github.com/eza-community/eza/blob/main/INSTALL.md#completions) document

**Comment by seanparkross** [comment]
THANKS @MartinFillon !
