### ISSUE TITLE
bug: Autocompletion Crash on eza v0.18.20 with Zsh

### ISSUE THREAD

**Issue by aryklein** [eza-community/eza#1038]
## Description:
Autocompletion (using tab tab) on eza version 0.18.20 running on Zsh crashes with the following error:

```sh
eza --binary --group --git Desk<tab><tab>
_eza:77: parse error near `\n'
```
## Step to reproduce it:
- Open Kitty terminal.
- Run Zsh shell.
- Type eza --binary --group --git Desk and press tab twice.

## Expected Behavior:
Autocompletion should work without errors.

## Notes:
- Downgrading to version 0.18.19 resolves the issue.
- The issue does not occur when using Bash.

**Comment by aryklein** [comment]
This PR https://github.com/eza-community/eza/pull/1037 should fix this issue

**Comment by cafkafk** [comment]
This was fixed in latest release https://github.com/eza-community/eza/releases/tag/v0.18.21
