### ISSUE TITLE
bug: tab completion does not work in zsh

### ISSUE THREAD

**Issue by JorySeverijnse** [eza-community/eza#1039]
error i get from just using eza without arguments:
_eza:77: parse error near `\n'

Upon looking in my history file i also see some entries with \n at the end of a command. When just running the gnu ls or exa command autocompletion works normally

- The version of eza being used v0.18.20 [+git]
- My shell is zsh and this does not happen in bash or nushell
- Linux 6.9.6-arch1-1      Arch Linux x86_64
I use oh my zsh with zsh-autosuggestions zsh-syntax-highlighting zsh-history-substring-search and powelevel10k

![image](https://github.com/eza-community/eza/assets/117462355/7d9c6909-9c80-4ab3-87e1-ed77cafb9451)

---

**Comment by thorio** [comment]
The issue is with missing backslashes in the zsh completions, apply this patch to `/usr/share/zsh/site-functions/_eza` to fix it locally. Pacman will overwrite it when the next update releases and all will be well again.
```patch
36,37c36,37
<         --no-symlinks"[Do not show symbolic links]"
<         --show-symlinks"[Explictly show symbolic links: for use with '--only-dirs'| '--only-files']"
---
>         --no-symlinks"[Do not show symbolic links]" \
>         --show-symlinks"[Explictly show symbolic links: for use with '--only-dirs'| '--only-files']" \
```

**Comment by notpeelz** [comment]
Duplicate of #1038 
PR is pending: #1037

**Comment by JorySeverijnse** [comment]
thanks
