### ISSUE TITLE
bug: `EZA_GRID_ROWS` does not have any effect on grid details view

### ISSUE THREAD

**Issue by LeoniePhiline** [eza-community/eza#1044]
This is a follow-up to https://github.com/eza-community/eza/issues/66#issuecomment-2198567463 and the discussion following it.

On `eza`, `main` branch, `EZA_GRID_ROWS` does not effectively prevent a grid view from being rendered if the threshold of configured number of rows is not reached.

The intention of `EZA_GRID_ROWS` is to force a details list view if there are only few items in the result set.

A fix is implemented in https://github.com/eza-community/eza/pull/1043.

**Comment by cafkafk** [comment]
> However, from a functionality perspective, as an end user I would expect this to apply to plain EZA_GRID_ROWS=1234 eza as well, without involvement of details views.

To be perfectly honest I'm extremely sick from covid so I can't really be of much help rn, but I vague get the sense that the current intention behind EZA_GRID_ROWS (whether it works or not) could be done differently, and maybe should be...

**Comment by LeoniePhiline** [comment]
> To be perfectly honest I'm extremely sick from covid

I wish you the best! Get well soon! ❤️‍🩹
