### ISSUE TITLE
feat:  Choice of icon

### ISSUE THREAD

**Issue by D-u-c-k-s-e-l** [eza-community/eza#1055]
It would be nice if there was an option to set certain folder/file names or paths to custom icons. (eg. setting `~/dotfiles` to `nf-md-folder_hidden` or choosing that any `*.fish` files should use the `nf-md-fishbowl` icon instead). Flags (like +x) or file types {link, directory, etc.} would also be good conditions to have on this.

This wouldn't easily be possible through environment variables, but I would love to see another layer of customizability added.

The main reasoning behind this is `ls` lets you choose colors, so an `ls` with icons should let you choose icons.

**Comment by PThorpe92** [comment]
this functionality will be available very soon when #840 is merged :tada:
