### ISSUE TITLE
bug: The 'sb' option in EZA_COLORS seems not working

### ISSUE THREAD

**Issue by pi314** [eza-community/eza#1056]
Basic information:

- The version of eza being used (`eza --version`):
v0.18.18

- The command-line arguments I was using:
`eza --long --binary --header`

- My shell and terminal:
Zsh + Mac default Terminal app

- My operating system and hardware platform:
macOS Sonoma 14.5 on MacBook Pro 2019

---

`sn=1;35:sb=0;35` doesn't separate number and units:
<img width="68" alt="截圖 2024-07-13 16 45 25" src="https://github.com/user-attachments/assets/2efb71ae-827d-44b4-aa8f-3f11d0950366">

I tried several combinations on `sn` and `sb`, and it seems like `sb` is not taking effect.
`ub`, `uk`, `um`, `ug`, `ut` are not working, either (`ug` and `ut` were not tested.)

Thank you for maintaining this project, though.
I was sad when exa became broken on MacPorts, and sadder when brew told me exa was disabled because it's not maintained.

**Comment by bew** [comment]
Might be a duplicate of #682.
Could you try the PR #975 maybe?

**Comment by pi314** [comment]
Thanks for the quick reply!

`--color-scale-mode=fixed` makes eza behave exactly what I need, but it feels like a workaround.

I guess I understand why you want to submit a pull request. The default behavior, that `sb` is silently ignored by `--color-scale-mode=gradient`, is a bit confusing.

----

(The following information is off-topic, I hope it worth writing down)

If I understand correctly, the color scaling feature "scales" the color to the range of size/age?
But the "color" and "scaling" here seems not very well-defined.

With `EZA_COLOR='reset'`, the color scale seems to be green→yellow→red and their gradients.
But in the middle I see an orange-ish color:
<img width="580" alt="截圖 2024-07-13 20 24 21" src="https://github.com/user-attachments/assets/bdab4b23-364a-4130-b072-56e2ecb1c458">

With `EZA_COLORS='sn=35'`, the color scale is the gradient of magenta:
<img width="543" alt="截圖 2024-07-13 20 27 28" src="https://github.com/user-attachments/assets/cca37415-a5ec-4ee9-a8c4-4a344dc9c4c1">

With `EZA_COLORS='sn=38;5;127'`, which is the closest color I can find from magenta, it become grayscale.
It looks like eza could only handle gradient starting from VT-100 8 colors:
<img width="539" alt="截圖 2024-07-13 20 34 10" src="https://github.com/user-attachments/assets/e84127c4-0d43-4e56-8906-509821ecc9b0">
Also `EZA_COLORS='sn=35'` and `EZA_COLORS='sn=1;35'` behaved the same.

It would be great if a gradient pattern could be defined from any color, maybe like calculating a curve from color17 to color231 that passes the specified color and use it for the color scale:
<img width="1596" alt="截圖 2024-07-13 20 46 54" src="https://github.com/user-attachments/assets/4817fa6f-29a9-48d7-8cad-5e9144c8f14c">

If that could be achieved, eza might no longer needs to ignore `EZA_COLORS` in gradient mode.
From there, gradient might be applied on `sn` and `sb`, separately.

Put those ideas aside, as a random eza user, I think your patch is the best thing we can do.
It sounds reasonable to ignore `scale.size` and `scale.age` if the `scale.mode` is already `fixed`.

**Comment by pi314** [comment]
It's a duplicate of #682.
