### ISSUE TITLE
bug: man page doesn't have `PERMISSION DENIED` status

### ISSUE THREAD

**Issue by sellithy** [eza-community/eza#1058]
`man eza`'s "EXIT STATUSES" section does not list the [`PERMISSION DENIED`](https://github.com/eza-community/eza/blob/main/src/main.rs#L509) (13) status. 

I'd do the PR myself if I had the dev setup.
Sorry if this is the wrong report type

**Comment by cafkafk** [comment]
> Sorry if this is the wrong report type

It's fine, thank for reporting! (worst case we can always change the label)

**Comment by chicks-net** [comment]
Would it be ok for me to tackle this?  I've read your contributing guidelines and I'm happy to follow them.

**Comment by cafkafk** [comment]
> Would it be ok for me to tackle this? I've read your contributing guidelines and I'm happy to follow them.

Yes, feel free to do so, it would be welcome :)

**Comment by chicks-net** [comment]
I think that covers the issue as defined.  I'm happy to clean up the Markdown a bit further if you're interested.
