### ISSUE TITLE
feat:  Displaying in Nushell-like table

### ISSUE THREAD

**Issue by Marin-Kitagawa** [eza-community/eza#1087]
`Nushell` shows a nice table when we execute the `ls` command. It'd be nice to have the table form in `eza` as well

**Comment by cafkafk** [comment]
I *think* this is already covered by #472, outside of nu-shell, I'm not sure we'll add a special eza feature for making this formatting, but it would be cool if we were interoperable with nu-shell (although, afaik, a lot of work!).

I'll close this as duplicate, lmk if that's incorrect :3
