### ISSUE TITLE
bug: Link dereferencing doesn't respect `-X` on main branch

### ISSUE THREAD

**Issue by cafkafk** [eza-community/eza#112]
Introduced in PR https://github.com/eza-community/eza/pull/32 in the merge hell.

This *should* not be hard to fix, I'll try to find time to take a look at it.

**Comment by cafkafk** [comment]
Broken symlinks does work on main
![2023-08-19_05-57](https://github.com/eza-community/eza/assets/89321978/c81a59d2-1ae1-4504-bac1-b34dcde0f46c)

**Comment by cafkafk** [comment]
symlinks to directories are acting as expected
![2023-08-19_06-01](https://github.com/eza-community/eza/assets/89321978/70b3a292-fc6f-4d52-90b2-bc5a341b56d9)

**Comment by cafkafk** [comment]
Links to regular files are broken
![2023-08-19_06-03](https://github.com/eza-community/eza/assets/89321978/9235acc6-db73-41c5-abf4-8d2e459cd1e2)

**Comment by cafkafk** [comment]
I've now confirmed that the error was introduced in 0397d5d052a282daaed7c6d88187d68b4a45ba92 and 5cc7bdfc3f2a7be43cfecadcaeb255594e05455a (those two should have been squashed, but it's too late now imo)

**Comment by cafkafk** [comment]
This was hairier than I expected, I'll revisit this at a later time when I've gotten some perspective.

**Comment by ariasuni** [comment]
I’d interested to understand what’s wrong in the last screenshot, because it totally does both what I’d expect it to do and what `ls` is doing

**Comment by cafkafk** [comment]
I've completely lost track of what the issue was tbh >_<

I have a vague feeling I discussed this somewhere on element recently, but tbh I can't remember. Maybe @sbatial can?

**Comment by sbatial** [comment]
So the issue title is kinda the opposite of what the issue is/was I think
See [the comment that led to the issue](https://github.com/eza-community/eza/pull/32#issuecomment-1666090428)

I noted that the file information (date etc.) is already dereferenced even without the flag.

I'm currently looking into whether I can still reproduce the issue and if it has already been fixed.

**Comment by sbatial** [comment]
So this is the result on the commit where the option was added.
![image](https://github.com/eza-community/eza/assets/46973479/7193ce51-efdd-482c-97ca-1380451a8ca8)

And here is ls (where the short form is `-L` btw. `-X` does sorting)
![image](https://github.com/eza-community/eza/assets/46973479/60595dae-6eb6-43e3-8672-62716fdc7fce)

The only difference I can see (with the information that is displayed at least) is the file size.
The date is correct (link creation without flag. corresponding file creation with it) but the size is always the one of the linked file.
(Which is also still the case on the current main branch)

**Comment by sbatial** [comment]
That's all I can see/remember.
I'm not in the Element group so if you discussed it recently, 'twasn't with me :sweat_smile:

**Comment by cafkafk** [comment]
Well, I guess we've learned that I should write more comprehensive issues...
