### ISSUE TITLE
404 error trying to download eza_0.19.2_amd64.deb from deb.gierens.de

### ISSUE THREAD

**Issue by RedSnt** [eza-community/eza#1128]
I'm not sure who runs the debian repo for eza, but it said there was an update to eza, version 0.19.2, but trying to download it gives a 404 error, file not found.  

![image](https://github.com/user-attachments/assets/589ae5f3-fd74-4df8-bae1-15f8651e61b9)

![image](https://github.com/user-attachments/assets/fcc27646-167e-4758-8c79-eb43a5be5fe7)

I feel like I've taken the wrong pills this morning, because I installed 0.19.0 via that mirror.  

So I'm wondering if this a problem that's being fixed?

**Comment by xaviergregor** [comment]
Hi !! Same here : 404  Not Found [IP : 82.165.23.185 80]

**Comment by cafkafk** [comment]
that's @gierens who runs that

**Comment by gierens** [comment]
Ah, thanks for reporting ... yeah I switched the DNS entry to my mirror node, because the cloud hosting the master node is gonna be down for a couple days ... I actually tested this, but apparently not rigorously enough ... -_- ... But no worries, I'll take are of it.

**Comment by xaviergregor** [comment]
> Ah, thanks for reporting ... yeah I switched the DNS entry to my mirror/backup node, because the cloud hosting the master node is gonna be down for a couple days ... I actually tested this, but apparently not rigorously enough ... -_- ... But no worries, I'll take are of it.

thank you

**Comment by gierens** [comment]
Alright, I think I fixed it ... can you try again?

**Comment by xaviergregor** [comment]
> Alright, I think I fixed it ... can you try again?

works fine, thank you

**Comment by gierens** [comment]
@RedSnt and for you?

**Comment by RedSnt** [comment]
@gierens 
Yep, this is working as intended now, thanks for the fix. Had some other problems messing with libwayland-server0, (almost bricking my system 😅), so I'm sorry it took me a while to get back to this. Closing as fixed.

**Comment by gierens** [comment]
Ah great! Thanks for the feedback! :)
