### ISSUE TITLE
bug: error render hyperlinks

### ISSUE THREAD

**Issue by XhstormR** [eza-community/eza#1131]
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`): v0.19.3
- The command-line arguments you are using: eza -l --hyperlink
- Your shell and terminal: fish shell, alacritty
- Your operating system and hardware platform: MacOS Darwin 23.3.0 x86_64 i386

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---

The / directory separator was incorrectly escaped as %2F, which prevented correct navigation to the file:
<img width="341" alt="image" src="https://github.com/user-attachments/assets/dd620970-7565-4869-977f-cf82e411ed49">

Correct: 
file:///Users/user/Downloads/pdf

**Comment by cafkafk** [comment]
Is this related to https://github.com/eza-community/eza/pull/882?

**Comment by XhstormR** [comment]
yes, since `/` is not an english alpha.
