### ISSUE TITLE
feat:  Customize order of columns in --long output

### ISSUE THREAD

**Issue by IgnacioJPickering** [eza-community/eza#1133]
The long output of `eza` is fixed and not customizable. Modifying the order of the displayed columns would be a nice feature to have.

For example, the file size column is in a different place than in `ls`, I understand some people may prefer that default and that's fine, but I would prefer for it to be in the traditional place.

**Comment by bew** [comment]
Duplicate of #148

**Comment by IgnacioJPickering** [comment]
Its true, I'll close this and add my +1 to that feature.
