### ISSUE TITLE
INSTALL.md misinformation

### ISSUE THREAD

**Issue by bodhilogic** [eza-community/eza#1139]
The text says:

> Cargo will build the eza binary and place it in $HOME/.local/share/cargo/bin/eza.

On my M3 Powerbook (Apple silicon device), the eza binary was actually placed in **$HOME/.cargo/bin/eza** 

BTW: Thank you for your application... I love it!

**Comment by cafkafk** [comment]
Ohh then we should probably correct it to include both (if the old option is still valid), or just remove that line, we probably don't need to be that specific.
