### ISSUE TITLE
bug: malformed hyperlinks when used with the kitty terminal (regression)

### ISSUE THREAD

**Issue by infradragon** [eza-community/eza#1142]
tested on eza v0.19.3 (cargo install), eza v0.19.3-1 (debian testing repo)
terminal is kitty 0.36.1-1+b1 (debian testing repo)
debian testing, system76 darter pro 9
tested without zshrc and kitty.conf

when using `eza --hyperlink`, the slashes seem to be url encoded:
![image](https://github.com/user-attachments/assets/3e27186b-3792-458e-927c-b5a8cd260d55)
which causes kitty to throw this error when clicking on any file:// uri from eza
![image](https://github.com/user-attachments/assets/66057dc0-bf34-434f-ad91-d8f30f5fd7f6)

The issue does not happen when using `ls --hyperlink=auto` and the file opens as expected
![image](https://github.com/user-attachments/assets/f196a07c-70dd-4d33-bcb0-2f4a6c304378)
another difference is that `ls` will specify my hostname in the uri (`76v2`), which could also be the source of the issue

i have tried forcing all file urls to open with xdg-open with an open-actions.conf:
``` 
protocol file
action xdg-open ${FILE_PATH}
```
but that didnt change anything

interestingly, xdg-open (and exo-open) refuses to open the malformed links outputted by eza when prompted to do so directly
![image](https://github.com/user-attachments/assets/30081fdf-0bb3-43b6-ab0b-c46a1bee1fe6)

kitty seems to be intercepting the malformed links
i know for a fact that this did not happen on older versions because it was working up until about a week ago

**Comment by infradragon** [comment]
something to note is that i have only tested this with kitty and xterm, and xterm does not support hyperlinks
i'm not sure what terminal is used during testing but it may be that it supports slashes that are url encoded while kitty doesn't

**Comment by cafkafk** [comment]
can you try on the latest version and see if this still happens?

**Comment by infradragon** [comment]
it doesn't... i just now realized that cargo installed 0.19.3 for whatever reason, it works when i download the generic gnu/linux build from github
i've also come to realize that the apt repo at deb.gierens.de only provides up to eza 0.19.2
