### ISSUE TITLE
bug: The `--absolute` option is unable to correctly retrieve the file's absolute path.

### ISSUE THREAD

**Issue by lunrenyi** [eza-community/eza#1151]
- System: macOS 14.6.1
  Terminal: VScode Terminal
  Shell: zsh 5.9 (x86_64-apple-darwin23.0)
  Eza version: v0.19.4 [+git]

- Bug: The `--absolute` option is unable to correctly retrieve the file's absolute path.
  ```sh
  mkdir -p a_dir
  touch a_dir/ab
  eza -l a_dir/ab --absolute
  ```
  <img width="641" alt="image" src="https://github.com/user-attachments/assets/1229d829-cddd-4f14-82d2-ea595fb6b16c">

**Comment by cafkafk** [comment]
For some reason, I can't repro this, but it makes sense looking at the fix... Might be a platform specific thing? It's odd :woman_shrugging:
