### ISSUE TITLE
bug: bad format when using --hyperlink & grep

### ISSUE THREAD

**Issue by ctf0** [eza-community/eza#1156]
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`): `v0.19.4`
- The command-line arguments you are using: `eza -l --hyperlink | grep 'somthing'`
- Your shell and terminal: `zsh` & `iterm2`
- Your operating system and hardware platform `mac m1 pro`

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---

- without hl
![Screenshot 2024-09-26 at 7 13 51 AM](https://github.com/user-attachments/assets/f439c39f-8b26-4f34-8ec2-e446c94c2fdf)

- with hl
![Screenshot 2024-09-26 at 7 14 39 AM](https://github.com/user-attachments/assets/c3699cf9-2503-48a9-8e40-d46cce9b8877)

**Comment by cafkafk** [comment]
Interestingly, I can't reproduce this on `0.19.4` on kitty, and kitty still interprets the hyperlinks correctly after they are output through grep.

To be honest, I think this is an iterm2 issue. I'm not sure how to report a bug to iterm2 (although this may well be a feature request), but that's probably the next step if you wanna solve this.

**Comment by ctf0** [comment]
oh ok, how about if possible, to disable some options based on the pipe filter ?

**Comment by cafkafk** [comment]
Well... sure, that may be another option, but I'm not sure if we have that kind of control... at the very least, perhaps open a separate issue as a feature requests, since it feels more like adding something new, not really anything that's broken on our end imo

**Comment by ctf0** [comment]
done, thank you, will close this one then.
