### ISSUE TITLE
feat:  Add json icon for .jsonc

### ISSUE THREAD

**Issue by Blubberland** [eza-community/eza#1166]
It looks like there the only thing to be done is to add this line
```rust
    "jsonc"    => Icons::JSON,             // 
```
to [this entity](https://github.com/eza-community/eza/blob/e7882ceb427cc13ab337d688fd650674f3478800/src/output/icons.rs#L343)
```rust
const EXTENSION_ICONS: Map<&'static str, char> = phf_map!
```
Not sure if this is correct. I'm not a developer.
I don't feel comfortable going through this whole pull-request procedure and it seems to be a bit much just for an icon.

**Comment by cafkafk** [comment]
> I don't feel comfortable going through this whole pull-request procedure and it seems to be a bit much just for an icon.

People are working on a configuration file that is more user facing, but it's a best effort thing.

**Comment by Blubberland** [comment]
I could find #139 and #897 which would - in case an agreed solution will be found - would solve this issue.
Seems like it would take some more time to do that. I'm not able to help unfortunatetly, but grateful for the work that's put into it.
Looking forward to a config file!

Thanks!
