### ISSUE TITLE
bug: `-f` fails to work with `-T` option

### ISSUE THREAD

**Issue by Xsakura1314** [eza-community/eza#1180]
# Summary

When using the `-f` with `-T` option, nothing is displayed, even if files are present in the directory.

# Reproduce
```
eza -T -f
```

# Versions
OS: Windows11 (23H2 x64)
Terminal: PowerShell7
eza: v0.20.1 (installed via scoop)

**Comment by cafkafk** [comment]
Can reproduce... odd! We had some changes to trees lately #1110, and a show directories last refactored some code that could be relevant #1172...
