### ISSUE TITLE
bug: Wrong file indicator is shown for directories, '*' instead of '/'

### ISSUE THREAD

**Issue by OnurKader** [eza-community/eza#1195]
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`)
- The command-line arguments you are using
- Your shell and terminal
- Your operating system and hardware platform

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---

- v0.20.3 from [Arch Linux Repos](https://archlinux.org/packages/extra/x86_64/eza/)
- `eza -lF`
- `zsh 5.9` and `alacritty` but happens with other terminals as well (`wezterm`, `contour`)
- Arch Linux, 64-bit
![2024-10-17_11-20-45](https://github.com/user-attachments/assets/e4005dd4-44e1-4f47-b8ba-55543bfaa39a)
A directory without the executable permission shows correctly, maybe something to do with
>Reuse filetype from DirEntry

In the release notes

**Comment by Cufoon** [comment]
totally wrong!
![image](https://github.com/user-attachments/assets/4031278a-03ef-4805-b19f-ef8462499149)

**Comment by jschpp** [comment]
I'm pretty sure this check
https://github.com/eza-community/eza/blob/7dbf234cb9b28cd0acb06b15909b1e0c058bb8ca/src/fs/file.rs#L337-L339
should be the other way around

**Comment by OnurKader** [comment]
![2024-10-17_13-52-46](https://github.com/user-attachments/assets/7afd3e48-0fe0-4f68-ba20-268642bac6d3)
I don't fully remember but I think the coloring for symlinked directories changed as well (they are colored like files) I assume this is the same issue

**Comment by jschpp** [comment]
I've tried the patch I mentioned and it seems to solve both problems

Patch:
```diff
diff --git a/src/fs/file.rs b/src/fs/file.rs
index 306d33e6..5cafcad2 100644
--- a/src/fs/file.rs
+++ b/src/fs/file.rs
@@ -334,7 +334,7 @@ impl<'dir> File<'dir> {
     #[cfg(unix)]
     pub fn is_executable_file(&self) -> bool {
         let bit = modes::USER_EXECUTE;
-        if self.is_file() {
+        if !self.is_file() {
             return false;
         }
         let Ok(md) = self.metadata() else {
```

## current eza build:
![grafik](https://github.com/user-attachments/assets/f3ca8226-8ad5-4d21-8fb4-689b4088870f)
![grafik](https://github.com/user-attachments/assets/32ebe6ba-56ab-40ef-b226-dfe6fd2d4053)


## patched build:
![grafik](https://github.com/user-attachments/assets/63f7e236-e8fa-4a11-a786-5b32bcede17b)
![grafik](https://github.com/user-attachments/assets/3f28502a-a1a2-4de0-beae-f2d910d34fc2)

**Comment by mrjackwills** [comment]
I'm not sure if this is a related issue, but starting with v0.20.3 executable files are no longer highlighted for me

v0.20.2
![Screenshot 2024-10-17 170426](https://github.com/user-attachments/assets/58d12de2-e866-4fb6-bb37-2885b6b474a7)


v0.20.3
![Screenshot 2024-10-17 170314](https://github.com/user-attachments/assets/346dae27-3249-4d28-88c9-a7fee2c9eba9)

**Comment by jwren0** [comment]
Also experiencing the same issue.

Just being a little nitpicky, I'd switch the `return false;` for `return true;` instead of negating the condition.

**Comment by cafkafk** [comment]
I've added your patch, thanks for the contribution :p
