### ISSUE TITLE
bug: eza 0.20.3 doesn't color things correctly based on their attributes/metadata

### ISSUE THREAD

**Issue by BurnerWah** [eza-community/eza#1196]
Eza 0.20.3 seems to have a regression where it shows incorrect colors for files based on their attributes/metadata (ex. if they're executable, a symlink, etc.)
I was able to reproduce this even if `LS_COLORS` wasn't set

Examples:

Symlinks using the wrong color
<img width="708" alt="Screenshot 2024-10-17 at 12 35 37" src="https://github.com/user-attachments/assets/86aa442f-9679-4f39-83e3-66f988f8fe0b">

Symlinks using the executable color, and executables using the regular file color
<img width="858" alt="Screenshot 2024-10-17 at 12 36 32" src="https://github.com/user-attachments/assets/7288974d-c406-4800-ace4-25adac875329">

Executables using the regular file color, with no `LS_COLORS` set
<img width="675" alt="Screenshot 2024-10-17 at 12 37 56" src="https://github.com/user-attachments/assets/3ee947c7-dbf3-4236-88d6-a3d118e4417b">

One socket using the executable color, while another uses the socket color 
<img width="564" alt="Screenshot 2024-10-17 at 12 40 41" src="https://github.com/user-attachments/assets/b33f495c-69f0-4b2c-9e70-3966b7c6f462">

---
Eza version: `v0.20.3 [+git]` (Detected with homebrew bottle, but reproduced with source build)
Command line arguments: None required
Shell: Fish 3.7.1
Terminal: kitty 0.36.4, iTerm2 3.5.5, WezTerm 20240203-110809,5046fc22
Operating System: macOS Somona 14.7
Hardware platform: arm64, Apple M1 Pro

**Comment by jschpp** [comment]
I'm pretty sure that this is the same problem as #1195 since the error seems to be in the way `eza` handles the `is_executable_file` wrong.

As far as I can tell the coloring/file indicators are marking everything __not__ a file as executable.

**Comment by BurnerWah** [comment]
> I'm pretty sure that this is the same problem as #1195 since the error seems to be in the way `eza` handles the `is_executable_file` wrong.
> 
> As far as I can tell the coloring/file indicators are marking everything **not** a file as executable.

That sounds very likely. Honestly I hadn't even noticed that the indicators for directories were wrong too lol.
