### ISSUE TITLE
bug: The filename, directory name, or volume label syntax is incorrect. (os error 123) when using PSDrives - "Repo:\\Git\test"

### ISSUE THREAD

**Issue by kbrucej** [eza-community/eza#1202]
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`)
- The command-line arguments you are using
- Your shell and terminal
- Your operating system and hardware platform

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---
eza version: v0.19.4
no arguments (or with any arguments the same)
PowerShell 7.4.5 / Windows Terminal
Windows 11 x86
----

```
> gci repo:

    Directory:  Repo:\

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----        2024-10-20     19:13        1   Git_Github_Bootcamp

> eza repo:
"repo:": The filename, directory name, or volume label syntax is incorrect. (os error 123)
```

**Comment by ChrisDenton** [comment]
PSDrives are a pure powershell concept. As [the docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-psdrive?view=powershell-7.4#description) say:

> Because temporary drives are known only to PowerShell, you can't access them by using File Explorer, Windows Management Instrumentation (WMI), Component Object Model (COM), Microsoft .NET Framework, or with tools such as net use.

Basically anything that's not powershell cannot understand them.

**Comment by cafkafk** [comment]
> Basically anything that's not powershell cannot understand them.

This makes me think we aren't gonna be able to fix this in a reasonable way, and we can chalk this up to another "powershell'ism"? If not LMK and I can reopen.
