### ISSUE TITLE
ci: v0.20.10: package `yoke v0.7.5` cannot be built because it requires rustc 1.71.1 or newer, while the currently active rustc version is 1.70.0

### ISSUE THREAD

**Issue by clavelm** [eza-community/eza#1249]
Hi,

I have a problem while attempting to build the v0.20.10.

Best regards,

Mathieu

---

If eza fails to compile, or if there is a problem during the build process, then please include the following information in your report:

- The exact eza commit you are building (`git rev-parse --short HEAD`)

    commit 0862493e (tag v0.20.10)

- The version of rustc you are compiling it with (`rustc --version`)

```
> rustc --version
rustc 1.70.0 (90c541806 2023-05-31)
```
```
> rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /var/services/homes/mathieu/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
1.70-x86_64-unknown-linux-gnu

active toolchain
----------------

1.70-x86_64-unknown-linux-gnu (overridden by '/volume1/homes/mathieu/eza/rust-toolchain.toml')
rustc 1.70.0 (90c541806 2023-05-31)
```
```
> rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for '1.70-x86_64-unknown-linux-gnu'
info: checking for self-update

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.82.0 (f6e511eec 2024-10-15)
    1.70-x86_64-unknown-linux-gnu unchanged - rustc 1.70.0 (90c541806 2023-05-31)

```

- Your operating system and hardware platform

    A Synology NAS (DS920+).

- The Rust build target (the _exact_ output of `rustc --print cfg`)

```
> rustc --print cfg
debug_assertions
panic="unwind"
target_arch="x86_64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="linux"
target_pointer_width="64"
target_vendor="unknown"
unix
```

- If you are seeing compilation errors, please include the output of the build process.

    (It’s a rerun of the command, that’s why previously built packages are not shown.)
```
> cargo install --path .
  Installing eza v0.20.10 (/volume1/homes/mathieu/eza)
    Updating crates.io index
error: failed to compile `eza v0.20.10 (/volume1/homes/mathieu/eza)`, intermediate artifacts can be found at `/volume1/homes/mathieu/eza/target`

Caused by:
  package `yoke v0.7.5` cannot be built because it requires rustc 1.71.1 or newer, while the currently active rustc version is 1.70.0
  Either upgrade to rustc 1.71.1 or newer, or use
  cargo update -p yoke@0.7.5 --precise ver
  where `ver` is the latest version of `yoke` supporting rustc 1.70.0

```

**Comment by cafkafk** [comment]
I can't reproduce this, and I don't think we have yoke as a dependency anywhere

**Comment by clavelm** [comment]
> I can't reproduce this, and I don't think we have yoke as a dependency anywhere

Reading the [`cargo install` documentation](https://doc.rust-lang.org/cargo/commands/cargo-install.html#dealing-with-the-lockfile) it says that "By default, the Cargo.lock file that is included with the package will be ignored. This means that Cargo will recompute which versions of dependencies to use, possibly using newer versions that have been released since the package was published."

Adding the flag `--locked` to the command fixes my problem, so the dependency to yoke must be added somewhere in the tree by a newer version of a dependency used when unrestricted by the Cargo.lock.

So the solution for someone having the same error is:
```
cargo install --path . --locked
```

Thanks for the help 😅
