### ISSUE TITLE
bug: Man page has stray option description relating to age

### ISSUE THREAD

**Issue by joliss** [eza-community/eza#1255]
The man page has [the following](https://github.com/eza-community/eza/blob/0862493ebded918454f97e7291537ce4e2643711/man/eza.1.md#L122-L126) lines:

```
`-w`, `--width=COLS`
: Set screen width in columns.

Valid options are `none`, `absolute` or `relative`.
The default value is `none`

`absolute` mode highlights based on file modification time relative to the past year.
`relative` mode highlights based on file modification time in relation to other files. `none` disables highlighting.
```

Everything from "Valid options" seems to relate to an unnamed option, not `--width`. (Perhaps this option doesn't exist anymore. I grepped the source for "relative" and "absolute" occurring near each other, and couldn't find anything.)

**Comment by joliss** [comment]
Browsing the commit history, this seems to have been added by @cafkafk and @aashirbadb in [288696db](https://github.com/eza-community/eza/commit/288696db10bea36b2c7952628f679f91a7298151#diff-dd75cdf47a825cc48d7a559083c373f8c6257659f45b0139df5752cf37c493c2R115-R120).

**Comment by cafkafk** [comment]
seems like this is a leftover from `--decay-mode` https://github.com/eza-community/eza/pull/526/commits/a55bdde0f5393834c59d7741328f4282d6a30270
