### ISSUE TITLE
bug: eza icons not showing up

### ISSUE THREAD

**Issue by alifiroozi80** [eza-community/eza#1275]
I have installed `eza` with `brew` on my MacOS.

Here are the results on two different terminals:

![Screenshot 2024-12-24 at 12 54 17 PM](https://github.com/user-attachments/assets/d867dcd7-efd0-486d-a815-e47cd26f1a08)

---

<img width="1265" alt="Screenshot 2024-12-24 at 12 59 30 PM" src="https://github.com/user-attachments/assets/17d552d3-26f9-430e-960d-6c38116e0bb0" />

- The version of eza being used (`eza --version`): 
```bash
$ eza --version
eza - A modern, maintained replacement for ls
v0.20.13 [+git]
https://github.com/eza-community/eza
```
- The command-line arguments you are using: `--icons`
- Your shell and terminal: `wrap` and `MacOS Terminal`
- Your operating system and hardware platform `darwin - arm64 (M1)`

---

**Comment by josedagama** [comment]
I'm having the exact same issue on gnome terminal:
![image](https://github.com/user-attachments/assets/df2f8dfe-cd26-4104-82cf-a91ade01e02a)

**Comment by cafkafk** [comment]
do you have nerdfonts installed? I think that brew doesn't install all system dependencies

**Comment by alifiroozi80** [comment]
Awesome @cafkafk!
Thanks 🍻

Here are my steps for anyone who sees this in the future:

1. Install NerdFonts:

```bash
brew install --cask font-hack-nerd-font # Or any nerd fonts you want.
```
2. Restart Warp (Or any terminal you have)
3. Then go to _Warp > Settings > Appearance_. A section called **Text** and a dropdown labelled **Terminal font**.
Your newly installed Nerd Font will be in that list from the first step, so you'll need to select it.

Here are the results:

![Screenshot 2024-12-29 at 12 30 02 PM](https://github.com/user-attachments/assets/71734668-ae65-4b70-a92f-db181db4a97e)

---

On the macOS default terminal:

Terminal > Settings > Profiles > Text > Font > Your newly installed font.

<img width="1167" alt="Screenshot 2024-12-29 at 12 35 44 PM" src="https://github.com/user-attachments/assets/24e26857-e5b9-4a16-973f-cd054ecefb67" />

---

### UPDATE:

Recently, I updated my Mac, and apparently, `brew` won't be enough. You should do this: 

1. Go to the [Nerd Font website](https://www.nerdfonts.com/font-downloads) and download the font you want
2. Follow [this](https://support.apple.com/guide/font-book/install-and-validate-fonts-fntbk1000/mac) instruction and import it to your system.
3. You're good to go

**Comment by tispratik** [comment]
Error: homebrew/cask-fonts was deprecated. This tap is now empty and all its contents were either deleted or migrated.

Do we have an alternative?

**Comment by gravitylow** [comment]
Looks like you can just run `brew install font-hack-nerd-font` now and don't need to run `brew tap`
