### ISSUE TITLE
Conventional Commits Version Standard

### ISSUE THREAD

**Issue by cafkafk** [eza-community/eza#160]
Conventional Commits also really ought to provide a standard way of declaring+detecting what version of the spec is being followed in a repo for any given commit. After thinking through a few designs, here's the standard I would propose (posting it here for initial feedback, but I'll probably post it as a proposal in the Conventional Commits repo soon):

The project adds a `COMMITS.md` file in the root of the repo, which must start with exactly the line `https://www.conventionalcommits.org/{{language}}/{{version}}`, where `{{language}}` is the language identifier (ignored by tooling - a tolerance to let projects use the link to their native language), and `{{version}}` is for example `v1.0.0` (optionally with a trailing `/`). Nothing else on that first line.

(In a precise spec I'd probably mandate that this string must be in UTF-8/ASCII, to reduce the odds that one popular implementation goes looser and all tools end up having to know how to detect or interpret other byte patterns.)

(For a proper spec, note that language identifiers are **not** always just two characters like `en`, but sometimes it's strings like `pt-br`, and a spec should either pin down precisely what it could be, or go explicitly loose and permit one URL path part, no matter what it is.)

Advantages/rationale:

Both tools and humans can know if Conventional Commit semantics apply to a commit, and which exact version. We can even know this with per-commit granularity by checking just the start of that file's contents for a given commit (for those who don't know, something like `git show` can do that without having to check out the whole commit) - and we get this per-commit granularity without having to specify the spec version in every commit. With that solved, the spec is much more free to evolve semantics without breaking interpretation by tooling.

By keeping it super simple (the version string and the URL string are one, it's the very first thing in the file by itself on the first line, there is no markdown syntax to parse, etc), we make it extremely simple+easy for tools to know what version of the spec is being used, humans can still see and understand a URL (and the markdown extension helps editors/viewers automatically style it as a link, make it clickable, etc), and there's a clear single source of truth.

By making the spec explicitly about the first line (so tools just look at the first line and ignore/tolerate the rest), it allows forward-compatibility with future spec changes or other unforeseen uses adding other information.

Discoverability is really high because it looks like one of the conventional about-this-repo files (all-uppercase, like README, CONTRIBUTING, etc), it points you right to the full documentation of that commit convention. It would also sort in basically the same place as a CONTRIBUTING file in an alphabetic listing - if I was looking for a "contributing" file and saw a "committing" file (as a dev who already knows what a "commit" is) I'd almost certainly think to look in it.

_Originally posted by @mentalisttraceur in https://github.com/eza-community/eza/issues/149#issuecomment-1686764574_

**Comment by cafkafk** [comment]
@mentalisttraceur 
> posting it here for initial feedback, but I'll probably post it as a proposal in the Conventional Commits repo soon

I think you should, I'd :+1: this.

Is it correct to summarize as:

- A COMMITS.md file should be added to the root of the repo.
- The first line of this file should have the format: https://www.conventionalcommits.org/{{language}}/{{version}}. Here, {{language}} is a language identifier (but is ignored by tools) and {{version}} is like v1.0.0.
- Only UTF-8/ASCII should be allowed for this string.
- Language identifiers can vary in format, but the specification should clearly define or be lenient about its structure.

**Comment by mentalisttraceur** [comment]
Thank you for the endorsement and the concise summary (which seems 100% correct).

Notes re: specifying `{{language}}`: turns out the "best current practice" for language tags is documented in [BCP 47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt). That seems just complex enough that it might be better (mainly due to human factors) to just specify that tools shoud accept anything matching the regex `[-a-zA-Z0-9_]*` for the language identifier ("should" because it seems too likely to prove correct/robust to be a mere "may", but seems needlessly against reusing a great BCP-47 implementation to be a "must").

**Comment by mentalisttraceur** [comment]
Proposed [upstream](https://github.com/conventional-commits/conventionalcommits.org) in issue 538.

**Comment by cafkafk** [comment]
I think this issue has served it's purpose here.
