### ISSUE TITLE
ci: Windows build is broken after afeac47 (#61)

### ISSUE THREAD

**Issue by daviessm** [eza-community/eza#169]
When checking my PR #167 doesn't break the Windows build I discovered that the Windows build has been broken for a while. Bisected to:

C:\Users\daviess\eza>git bisect bad
afeac47c13f81213b48c1d3b317ef7862061e14d is the first bad commit
commit afeac47c13f81213b48c1d3b317ef7862061e14d
Author: Christian Göttsche <cgzones@googlemail.com>
Date:   Sun Apr 25 15:00:58 2021 +0200

Which is #61.

**Comment by PThorpe92** [comment]
Glad to see someone finally jumping on
Windows Support #102 

as I know from experience, some poor souls are sometimes forced to use such terrible software (windows). It would be nice if they weren't excluded from using Eza :)
