### ISSUE TITLE
feat: update with Homebrew installation instructions

### ISSUE THREAD

**Issue by adiabatic** [eza-community/eza#200]
`eza` just showed up in my new-formulae list, and `brew install eza` does what you'd expect.

**Comment by cfxegbert** [comment]
`brew install eza`

It seems to install eza-0.11.0 and exa-0.10.1. We should reach out to the maintainer to separate `exa`

**Comment by cafkafk** [comment]
This has been added to the documentation, thanks for the suggestion! :heart:
