### ISSUE TITLE
feat: ebuild for Gentoo

### ISSUE THREAD

**Issue by daviessm** [eza-community/eza#201]
Generate a Gentoo ebuild upon release, and perhaps automatically submit it to the Guru overlay.

Can someone assign this to me?

**Comment by mschilli87** [comment]
If exa is in the portage tree, maybe a bug should be opened to mask it as unmaintained.

**Comment by daviessm** [comment]
> If exa is in the portage tree, maybe a bug should be opened to mask it as unmaintained.

Yeah, I'd prefer to have a replacement ready to go when we do that.

**Comment by daviessm** [comment]
Depends on #236 as the project declares an MSRV of 1.70.0 but Gentoo has only stabilised 1.69.0. `eza` actually works with everything back to 1.65.0.

**Comment by sevz17** [comment]
Hi, I am the maintainer of exa in gentoo, as per bug [931737](https://bugs.gentoo.org/913737) I added eza to the portage tree and masked exa in gentoo/gentoo#32705

**Comment by sevz17** [comment]
And I guess that a Gentoo entry should be added to the readme, do you want me to do it?

**Comment by daviessm** [comment]
> And I guess that a Gentoo entry should be added to the readme, do you want me to do it?

If you're happy to, sure! I was hoping to figure out GitHub actions and write a `cargo ebuild` script for each release but if you're happy to maintain `eza` in whatever way you see fit then please continue!

**Comment by sevz17** [comment]
> ... I was hoping to figure out GitHub actions and write a `cargo ebuild` script for each release but if you're happy to maintain `eza` in whatever way you see fit then please continue!

No worries, I can manage.

**Comment by daviessm** [comment]
Cool, closing this issue then.

**Comment by daviessm** [comment]
@sevz17 I just noticed that the 0.11.1 ebuild still has a dep on `>=virtual/rust-1.70.0` - should be `1.65.0`.
