### ISSUE TITLE
feat: Dynamically link libgit2.so

### ISSUE THREAD

**Issue by kpcyrd** [eza-community/eza#214]
hi!

The `Cargo.toml` currently enables the `vendored-libgit2` feature unconditionally, I think this should default to off with an option to enable it (similar to the `vendored-openssl` feature that can optionally be enabled).

Thanks!

**Comment by cafkafk** [comment]
Yes, this was introduced in #192 to ease packaging for debian/ubuntu. Perhaps @gierens can enable do this and enable the feature in the deb repository?
