### ISSUE TITLE
feat: provide arm64 and armhf debian packages

### ISSUE THREAD

**Issue by uwe-schwarz** [eza-community/eza#217]
After following the instructions for debian/ubuntu:

N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://deb.gierens.de stable InRelease' doesn't support architecture 'armhf'

and

N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://deb.gierens.de stable InRelease' doesn't support architecture 'arm64'

**Comment by gierens** [comment]
@uwe-schwarz I've added `arm64` and `armhf` packages cross-compiled with `aarch64-unknown-linux-gnu` and `arm-unknown-linux-gnueabihf` targets, can you test if they work?

**Comment by gierens** [comment]
@cafkafk as usual cross compilation is a bit of a nightmare, fortunately there is this https://github.com/cross-rs/cross ... it however doesn't properly run on my workstation at the moment, therefore it might take me a couple of days to figure out how to properly refactor my build script for this and make a PR. Until then we might wanna keep this open.

**Comment by uwe-schwarz** [comment]
> @uwe-schwarz I've added `arm64` and `armhf` packages cross-compiled with `aarch64-unknown-linux-gnu` and `arm-unknown-linux-gnueabihf` targets, can you test if they work?

I can confirm that both versions are working. Thanks!

**Comment by cafkafk** [comment]
> @cafkafk as usual cross compilation is a bit of a nightmare, fortunately there is this https://github.com/cross-rs/cross ... it however doesn't properly run on my workstation at the moment, therefore it might take me a couple of days to figure out how to properly refactor my build script for this and make a PR. Until then we might wanna keep this open.

Did you see this PR https://github.com/eza-community/eza/pull/211? It doesn't work for some platforms on my machine yet (those I commented out failed), but that's my current attempt at using cross, and it's how the binaries were generated for last release. But it's very much just a first attempt so I had something ready for Monday.

**Comment by gierens** [comment]
Ah, if only I would seen that earlier :D ... but great there are release binaries now, then I can use those directly and don't need to compile them myself again for the deb packages :)

**Comment by gierens** [comment]
Since we now have both archs on the release pages and deb repo this can be closed.
