### ISSUE TITLE
bug: Windows defender flags `eza` as a trojan (false positive)

### ISSUE THREAD

**Issue by egelja** [eza-community/eza#218]
I downloaded the latest version of `eza` (0.11.0) from github releases, and Windows defender flagged it as malicious as soon as the download finished. The message from Defender is shown below.

![image](https://github.com/eza-community/eza/assets/76668284/0965882b-62b6-4674-8199-9d97385e9bfb)

The SHA-256 hash of the file is `480bceb36fe41c436d4ae3816333e0dcb2c9afbc5da56a8fb78315faaf5dc24f`. VirusTotal analysis can be found [here](https://www.virustotal.com/gui/file/480bceb36fe41c436d4ae3816333e0dcb2c9afbc5da56a8fb78315faaf5dc24f/detection).

**Comment by egelja** [comment]
Interestingly, according to VT, `eza` seems to be making web requests too.

![image](https://github.com/eza-community/eza/assets/76668284/0ef5e53f-f9de-4c6c-b5b5-f631f8663fc6)

**Comment by PThorpe92** [comment]
Thank you for reporting this :+1: 

Looking into this myself right now, and I assigned our resident Windows guy. 

I know windows defender will pretty much alert to any exe that isn't digitally signed with a cert authority. We will have to figure that out. Web requests dont make sense to me though at all. Looking into this

**Comment by cafkafk** [comment]
> The SHA-256 hash of the file is `480bceb36fe41c436d4ae3816333e0dcb2c9afbc5da56a8fb78315faaf5dc24f`. VirusTotal analysis can be found [here](https://www.virustotal.com/gui/file/480bceb36fe41c436d4ae3816333e0dcb2c9afbc5da56a8fb78315faaf5dc24f/detection).

This is the same as is generated through cross
```
480bceb36fe41c436d4ae3816333e0dcb2c9afbc5da56a8fb78315faaf5dc24f  target/x86_64-pc-windows-gnu/release/eza.exe
```

This is very odd... could it just be a hash collision? I'm not sure how VT works.

**Comment by egelja** [comment]
> This is very odd... could it just be a hash collision? I'm not sure how VT works.

I doubt it — the file wasn't uploaded until today.

![image](https://github.com/eza-community/eza/assets/76668284/2c3ffd9e-1880-48be-a678-d974b85cb6ee)

There are some more hashes in the [details tab on VT](https://www.virustotal.com/gui/file/480bceb36fe41c436d4ae3816333e0dcb2c9afbc5da56a8fb78315faaf5dc24f/details) if you want to check.

**Comment by cafkafk** [comment]
The cross compilation is done via https://github.com/cross-rs/cross, I tested `https://github.com/cross-rs/cross` on another project of mine and it didn't cause this issue, so it's not that.

**Comment by cafkafk** [comment]
This should just be a false positive, I've submitted a request to "Microsoft Security Intelligence" to have the binary reassessed, hopefully it won't take too long.

**Comment by cafkafk** [comment]
Microsoft got back to us:

![2023-09-08_04-52](https://github.com/eza-community/eza/assets/89321978/f8d46a4a-dd55-461c-8693-518aae50ef16)

![2023-09-08_04-53](https://github.com/eza-community/eza/assets/89321978/4a14ee1c-60a5-4f22-9f22-99f50b7b22f7)

```
At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
     3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus
```

I couldn't find a way to contact Bkav Pro, so I'm closing this as solved for now.
