### ISSUE TITLE
bug: `-T --tree` line-drawing characters color hard to see

### ISSUE THREAD

**Issue by akiirui** [eza-community/eza#220]
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`)
  - v0.11.0
- The command-line arguments you are using
  - `eza -T`
- Your operating system and hardware platform
  - Arch Linux 

bug: `-T --tree` line-drawing characters color hard to see in dark background console.

![Screenshot from 2023-09-08 02-27-06](https://github.com/eza-community/eza/assets/3736910/90f32615-a44f-4f7a-b027-f9c8296e5c72)

**Comment by smackysnacks** [comment]
`EXA_COLORS="xx=''" eza -T`

See https://github.com/orgs/eza-community/discussions/209

**Comment by cafkafk** [comment]
Closing in favor of #240
