### ISSUE TITLE
feat: add completion files to deb package

### ISSUE THREAD

**Issue by Marsup** [eza-community/eza#230]
Hello,

It seems that deb packages don't contain any completion file. I have looked at all the packages that were downloadable on the repo, it doesn't seem like a recent issue, they have never been there.

I'm not a Rust dev at all, so I don't know how it should work, but the configuration section in the Cargo.toml file seems right to me. Or at least it's exactly how it was in exa. So maybe things changed in the packaging tool?

**Comment by gierens** [comment]
Yeah, you're totally right ... they were never there because I forgot to add them :D ... my bad, I'll fix this!

**Comment by cafkafk** [comment]
If it's helpful this is how it's done in `nixpkgs`, ofc you don't have access to stuff like `installManPage`, but thought it might inspire how this could be done.

https://github.com/NixOS/nixpkgs/blob/3a2786eea085f040a66ecde1bc3ddc7099f6dbeb/pkgs/tools/misc/eza/default.nix#L37C2-L46C6

**Comment by gierens** [comment]
Although this will be merged after v0.12.0, I already added the completio files to the v0.12.0 deb package.
