### ISSUE TITLE
feat: Support timezone for Windows

### ISSUE THREAD

**Issue by tadashi-aikawa** [eza-community/eza#232]
First, Thank you for your great work :)

It would be nice to be able to display the time taking the timezone into account, such as `ls` and `dir`.

![image](https://github.com/eza-community/eza/assets/9500018/7cc3ef8f-296e-4b33-a678-b3609ede874d)

**Comment by tadashi-aikawa** [comment]
Might https://github.com/eza-community/eza/pull/58 also be relevant?

**Comment by daviessm** [comment]
#227 should fix this.

**Comment by tadashi-aikawa** [comment]
It works in v0.11.1! Thanks a lot ❤️
