### ISSUE TITLE
bug: can't see the dashes in permission

### ISSUE THREAD

**Issue by smartding** [eza-community/eza#234]
I'm using eza v0.11.0 in Arch Linux.

When I run "eza -l", the dashes in the permission column are invisible, as shown in the figure below:
![image](https://github.com/eza-community/eza/assets/16423944/fca37b71-0527-486f-b4a0-e552cb5d0681)

I can see the dashes when color is disabled.

As a comparison, exa doesn't have this issue, as shown in the figure below:
![image](https://github.com/eza-community/eza/assets/16423944/6ef15760-17ff-4a78-b3b5-a5a955c2703b)

**Comment by holmesrichards** [comment]
The dash color (along with other punctuation) can be changed in the EXA_COLOR environment variable, e.g.
`EXA_COLORS="xx=37"` will make the punctuation white. Does that fix it for you?

**Comment by kevinquillen** [comment]
Had this same issue switching from exa.

Adding `export EXA_COLORS="xx=37"` to my zshrc fixed the issue.

**Comment by PThorpe92** [comment]
@smartding 

To see if #237 will close this issue, we are looking for some feedback from users. It adds "Bright" color options, and switching from Black to Dark Gray for the default punctuation color may solve this on some terminals. The difference doesn't look like much on mine in particular, but it very well may make it show up.

**Comment by cafkafk** [comment]
Closing in favor of #240
