### ISSUE TITLE
bug: `--all --all/-aa` needs documentation

### ISSUE THREAD

**Issue by NekoiNemo** [eza-community/eza#238]
v0.11.0 [+git]

When being executed with `--all` flag, eza doesn't show the `.` and `..`  dirs (unlike both ls and exa). There also doesn't seem to be an `--almost-all/-A` flag that should have this type of behaviour attached to it. `-la` is an good way to see owner/perms of the current dir, so i hope this is a bug and not an intentional decision

**Comment by holmesrichards** [comment]
It apparently is intentional. Use `eza --all --all` to show `.` and ``..``.

**Comment by NekoiNemo** [comment]
Oh. Then i guess the bug is that this is not documented in `--help`
