### ISSUE TITLE
tracking issue: punctuation color

### ISSUE THREAD

**Issue by cafkafk** [eza-community/eza#240]
Exa was "deprecated" last week, and this lead to an influx of users. This is
great as it has made UX issues more visible, because we now get more feedback.

On of those issues was introduced in #64, a PR where colors were changed to no
longer be "hardcoded". While not having "hardcoded" colors makes sense, we
should find some default that works for the vast majority of users.

This issue exists to track this effort.

Currently, my goal is to merge #237 before monday in time for the `0.11.1`
release. If that goes out and doesn't fix it for everyone, we'll have to
further look into this.

Casued by: #64
PRs: #237
Affects: #234, #220, #208, #209

**Comment by PThorpe92** [comment]
I assume u meant your goal is to merge #237 before release? 

Anyone's feedback on the color change referenced in the PR would be appreciated. I did my best to find out what color your background would have to be to make these invisible... and I came up with this.
## New
![image](https://github.com/eza-community/eza/assets/121899304/d8e43f23-ee38-4367-bbd0-7d166385173a)
## Current

**Comment by cafkafk** [comment]
> I assume u meant your goal is to merge #237 before release?

:woman_facepalming:

**Comment by smartding** [comment]
I built from the latest the commit(93721349), the new default color for punctuations is much more visible in my color setting now:

New color:
![image](https://github.com/eza-community/eza/assets/16423944/b5f2e37e-0bd8-4e53-ac4a-3799c8c56ec0)

**Comment by cafkafk** [comment]
Closed as fixed
