### ISSUE TITLE
bug: CI runners fail to start

### ISSUE THREAD

**Issue by cafkafk** [eza-community/eza#244]
> Waiting for CI to pass, but this does build for me locally and should be trivial to revert if it did do any harm.

Those last two CI runners failed to start yesterday as well, not sure why.

_Originally posted by @daviessm in https://github.com/eza-community/eza/issues/236#issuecomment-1712896497_
           
#236

**Comment by PThorpe92** [comment]
Hmm.. we were wondering about this on gitter as well in regards to #195

**Comment by cafkafk** [comment]
Yeop, solved it
