### ISSUE TITLE
bug: deb installation instructions use ascii-armored GPG key

### ISSUE THREAD

**Issue by raylu** [eza-community/eza#259]
in an ubuntu 20.04.6 container, I followed the deb instructions but get
```
$ sudo apt update
W: http://deb.gierens.de/dists/stable/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/gierens.asc are ignored as the file is not readable by user '_apt' executing apt-key.
W: GPG error: http://deb.gierens.de stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY EC29E2090CE3FD43
E: The repository 'http://deb.gierens.de stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

this is because the GPG key is armored. de-armoring it works

```
$ wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/gierens.asc
$ sudo apt update
$ sudo chmod o+r /etc/apt/sources.list.dgierens.list 
$ apt list eza
Listing... Done
eza/stable 0.11.1 arm64
```

**Comment by gierens** [comment]
Thanks for the issue and the hint, I'll update the `README.md` tomorrow.

**Comment by dng-nguyn** [comment]
For some reason the opposite worked for me. When I first tried to install the program, the `wget` line outputted unrecognizable characters. After a few minutes of troubleshooting, I removed the `gpg --dearmor` and it worked as normal.
![image](https://github.com/eza-community/eza/assets/133786254/0a311cf9-07f0-484a-ae87-27b6d5098fd0)

**Comment by gierens** [comment]
@PThorpe92 ... I don't know what else to say then, I told you so <3

**Comment by raylu** [comment]
the unprintable characters are expected (that's what ascii-armoring is meant to prevent). that doesn't indicate an issue and actualy means it's working

are you saying that, with the de-armored key, you weren't able to install eza? if so, what OS are you on (`cat /etc/issue*`) and what did it say when you tried to `apt update` @dng-nguyn?

if there is indeed a problem with de-armoring, it has nothing to do with containers. perhaps an older version doesn't support de-armored keys (unlikely) or a newer version wants to use `/etc/apt/keyrings` instead

**Comment by gierens** [comment]
Alright I googled around a bit, documentation on this is seems a little thin or often outdated. From what I understand the current suggestion is to store the key online in armored format but locally have it dearmored in `/etc/apt/keyrings`. I do agree however that `tee`ing the dearmored format like this however does produce this very ugly and maybe confusing output. So either using `sudo gpg --dearmor -o ...` or `tee` with `1>/dev/null` is probably a good idea.

There were some comments suggesting that `/etc/apt/keyrings` might not even be present by default on all systems. To check this and verify the process with dearmoring in general I will spin up a few VMs tomorrow with the latest two releases of Ubuntu and Debian and test it for myself once more. Following that I will update the `README.md` with the then hopefully final recommendation.

**Comment by dng-nguyn** [comment]
I am currently on debian 12 bookworm. On my first, clean installation program, I ran the provided commands (the one with `gpg --dearmor`) and as far as I can remember it showed that the repository was not signed and eza had no installation candidate.

**Comment by raylu** [comment]
I was gonna poke around in a container but it looks like deb.gierens.de (resolving to 138.246.234.80 for me) is down right now

**Comment by gierens** [comment]
> I was gonna poke around in a container but it looks like deb.gierens.de (resolving to 138.246.234.80 for me) is down right now

Cooling issue at the data center, fabulous, I'll take care of it but could take a couple hours ... gonna try to make the repo high available with multiple hosts once it's up again.
