### ISSUE TITLE
bug: The deb repo appears to be broken

### ISSUE THREAD

**Issue by evilhamsterman** [eza-community/eza#260]
Trying to install eza using the Debian repos results in an error due to incorrect file size 

```
 File has unexpected size (565828 != 565804). Mirror sync in progress? [IP: 138.246.234.80 80]
  Hashes of expected file:
   - SHA512:38acd2c323d860cad2eed95762ba7fb8b2d47e283d5ae7586dc6ca53d193e7273746bc82b21c126c2283093951b8b27999849aa96f8322389e69c8aeb6d6b9d0
   - SHA256:147873bbab4f4ca9406fddfc15d09ee31246dc2260d7aa17d29eab11a45034ab
   - SHA1:d6e9ab22923dde796ffb2636e66e0b3b01f82f1f [weak]
   - MD5Sum:97acb7769af59c5a26152f460a5a4593 [weak]
   - Filesize:565804 [weak]
```

---

**Comment by gierens** [comment]
Thanks for reporting this. There seems to have been some invalid repo update when I pushed the current release. I rewrote my packaging script today and had to readd the package a few times. Maybe that caused the mess.

I removed and readded all v0.11.1 packages again and think it should work now. Can you do a `sudo apt clean && sudo apt update` and then try to upgrade `eza` again?

**Comment by PThorpe92** [comment]
Just right now updated eza (0.11.1) successfully on my work laptop (ubuntu) :+1: 

Seems to be all fixed

**Comment by evilhamsterman** [comment]
Works great 👍
