### ISSUE TITLE
bug: --git-repos symbol meaning and dash colors

### ISSUE THREAD

**Issue by holmesrichards** [eza-community/eza#281]
v0.11.1 [+git]
Linux Mint 21.2 Cinnamon / Intel

Two things about --git-repos: First, from comparing with --git-repos-no-status I infer the first column is a status indicator but it's not obvious to me what the pipe symbol means here. Some words in the man page would be helpful.

Second, the dashes in those columns are not given the same color as punctuation elsewhere (and are not documented as having their own color):

![image](https://github.com/eza-community/eza/assets/56895621/1ce29c94-3b78-48bb-a930-59e853b4559b)

But the status can be a dash and in that case it *is* colored; however, it apparently is bold, unlike the other dashes:

![image](https://github.com/eza-community/eza/assets/56895621/695724a9-0350-474b-874f-d938bc84299a)

Expected behavior:
* Information on status symbols in man page
* Dashes consistently colored and not bold

**Comment by PThorpe92** [comment]
Definitely some documentation and consistency needed here :+1:

**Comment by cafkafk** [comment]
Did #283 solve this or is there more to be done here?

**Comment by cafkafk** [comment]
Seems solved for now.
