### ISSUE TITLE
feat:  Displaying binary attributes

### ISSUE THREAD

**Issue by cfxegbert** [eza-community/eza#290]
Mac OS X Ventura has added the `com.apple.provenance` on files that contains an 11-byte binary reference.  The best explanation I could find for this attribute is https://mjtsai.com/blog/2023/03/16/ventura-adds-com-apple-provenance/.  Doing a `eza -l@` will try to display this binary data.
![Screenshot 2023-09-12 at 5 31 50 PM](https://github.com/eza-community/eza/assets/38872275/1bca37ac-ec21-45e9-ae83-dbe3f58f077e)

eza should detect non UTF-8 strings in attributes and either not display the attribute value, display a base64 version, or display a placeholder like `<binary>`.  If we display a base64 version should we truncate the length of the value displayed?

**Comment by cafkafk** [comment]
> eza should detect non UTF-8 strings in attributes and either not display the attribute value, display a base64 version, or display a placeholder like <binary>

Another option might be to display hexadecimal, that's probably what most people that would ever need this would find most useful right?

**Comment by cfxegbert** [comment]
Not sure if hexadecimal or base64 would be better.  Base64 would produce shorter output.

com.apple.lastuseddate#PS also has binary data.  It seems to be two 64-bit little ended words.  First word is a unix date and the second word is subseconds in nano-second.  Do we want to get into the business of trying to decode the data?

**Comment by cfxegbert** [comment]
Here is some good docs on the extended attributes.  They can be quite large.  https://www.real-world-systems.com/docs/xattr.1.html

**Comment by cafkafk** [comment]
> Do we want to get into the business of trying to decode the data?

I'm in no way against that, although perhaps we should move such an effort into a library and then use that. But also, I'm not really a mac user, so I'm probably not the one that's gonna do all the legwork. 

So I guess, if you or someone else wanna do it I would merge it, but we don't have to do it.

**Comment by piechologist** [comment]
This is also an issue with extended SELinux attributes on RHEL/AlmaLinux/etc.

For instance, listing ~/ .ssh with `eza -la@ ~` prints the xattr `security.sehash=` followed by binary gibberish that messes up the terminal state.

eza's man page says `-@, --extended: List each file’s extended attributes and sizes` so, printing just the xattr's name and size may be sufficient? That's what `ls -l@` does on macOS. If someone needed the value, they could use a specialized tool like `xattr` on macOS.

**Comment by cfxegbert** [comment]
Fixed in v0.16.1
