### ISSUE TITLE
Cannot reach repo

### ISSUE THREAD

**Issue by mpauper** [eza-community/eza#296]
Hello,

Thanks for taking care of `eza`, it was nice to find an immediate refuge after `exa`!

I am on pop-os, and I used the .deb installation method. It worked fine 2 days ago. 

I am trying to `apt update` but apparently the repository is unreachable?

```
Error: http://deb.gierens.de stable InRelease
  Could not connect to deb.gierens.de:80 (138.246.234.80), connection timed out
```

**Comment by cafkafk** [comment]
See: [#259](https://github.com/eza-community/eza/issues/259#issuecomment-1717031299)
> > I was gonna poke around in a container but it looks like deb.gierens.de (resolving to 138.246.234.80 for me) is down right now

> Cooling issue at the data center, fabulous, I'll take care of it but could take a while ... gonna try to make the repo high available with multiple hosts once it's up again later the day.

This will likely be resolved shortly.

**Comment by sandenbergmelo** [comment]
Same with me on Ubuntu 22.04. I can't update eza.

**Comment by cafkafk** [comment]
This should be resolved now.
