### ISSUE TITLE
bug: derefence flag documentation missing in manpage/--help

### ISSUE THREAD

**Issue by KucharczykL** [eza-community/eza#297]
Version: v0.11.1 [+git]
OS: openSUSE Tumbleweed

Description of the newly added de-reference feature (#32) is missing from both the manpage and command-line `--help`.

**Comment by cafkafk** [comment]
I see. A fix for this should likely be made after #195, but also currently, the dereference flag is a little shaky in general and needs some attention #112. =

**Comment by KucharczykL** [comment]
Still an issue

**Comment by holmesrichards** [comment]
Wasn't this fixed in https://github.com/eza-community/eza/pull/503 ?

**Comment by cafkafk** [comment]
> Wasn't this fixed in #503 ?

I think so! I'll close this for now.
