### ISSUE TITLE
Add eza to winget

### ISSUE THREAD

**Issue by sandenbergmelo** [eza-community/eza#298]
Adding eza to winget would make installation on Windows much easier.

**Comment by cafkafk** [comment]
There is some documentation about doing this here: https://learn.microsoft.com/en-us/windows/package-manager/package/ for anyone up for doing this.

**Comment by sitiom** [comment]
On it:
- https://github.com/microsoft/winget-pkgs/pull/119560

[Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser) would have to be set up in this repo for automatic publishing. @cafkafk are you willing to accept a PR for this?

**Comment by cafkafk** [comment]
> @cafkafk are you willing to accept a PR for this?

I have to read about it I'll get back to you as soon as possible.
