### ISSUE TITLE
bug: `yarn.lock` file icon can not find itself

### ISSUE THREAD

**Issue by sukvvon** [eza-community/eza#301]
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`)
- The command-line arguments you are using
- Your operating system and hardware platform

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---

![스크린샷 2023-09-14 오전 12 54 55](https://github.com/eza-community/eza/assets/66409882/d0cb81df-ffda-4d5d-8d88-5356cf75958b)

i heard `eza` is forked from `exa` but `yarn.lock` file's icon has something wrong
please fix it  🙋🏻‍♂️

im using font, `MesloLGS NF`
opating system: macOS ventura 13.5

**Comment by PThorpe92** [comment]
What version of NerdFonts are you using?

**Comment by cfxegbert** [comment]
If you look on https://www.nerdfonts.com/cheat-sheet it should be using the icon nf-seti-yarn.  Make sure you have the latest version of the font https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Meslo.zip

**Comment by sukvvon** [comment]
@PThorpe92 i'm using latest verion of 'MesloLGS NF'

**Comment by PThorpe92** [comment]
Are you sure they are updated to Nerd Fonts 3?
https://github.com/romkatv/powerlevel10k/issues/2217

If you look at the bottom of that issue, it seems others have had problems with that font after NerdFonts updated to 3.0

**Comment by sukvvon** [comment]
@PThorpe92 Thanks! i updated it, and it works!
it's my mistake... 🙏😇
