### ISSUE TITLE
bug: zsh autocompletion failing

### ISSUE THREAD

**Issue by ChrisNeugebauer** [eza-community/eza#308]
Current version: v0.11.1
OS: EndeavourOS
Shell: zsh 5.9

What I did:
Listing a subdirectory or file using eza amd using autocompletion, like `eza .con` followed by a tab for auto completion or `eza .zshr` followed by a tab.

What I expected:
Autocompletion to `eza .config` and `eza .zshrc` respectively.

The unexpected behaviour:
An error message, in all cases the same:

```
(eval):1: _exa: function definition file not found
(eval):1: _exa: function definition file not found
(eval):1: _exa: function definition file not found
``` 
The same error occurs when completing file-/directorynames without a . at the beginning. I tested with bash, autocompletion works fine over there. Zsh autocompletion works fine for every other program.

**Comment by MartinFillon** [comment]
https://github.com/ogham/exa/issues/585 this bug exists but has never been reproduced
If you installed exa using a package manager I recommand re cp the completion file of zsh to the right directory https://stackoverflow.com/questions/25290751/where-to-place-zsh-autocompletion-script-on-linux

**Comment by ChrisNeugebauer** [comment]
I can't figure out how to do that, sorry. Everything I find is about using oh-my-zsh, which I don't. Closing because bug is known(?) and workaround got nothing to do with eza/exa?

**Comment by MartinFillon** [comment]
Okay I will help you.
first clone the repo:
```sh
git clone https://github.com/eza-community/eza.git
```

then you want to do something like

```sh
echo 'export FPATH="<path to eza repo>/completions/zsh:$FPATH"' >> ~/.zshrc
```
This will add eza completions to your FPATH which is the list of directories used by zsh to complete your command.

Then just do:

```sh
source ~/.zshrc
```
