### ISSUE TITLE
feat:  show special chars as shown by ls

### ISSUE THREAD

**Issue by alaymari** [eza-community/eza#311]
`eza`, formerly `exa` and `lsd` all are almost compatible with `ls`. I like the replacement better, except for the display of filenames with specials chars like a space, #, et al.  

I have a directory `VirtualBox VMs` in my $HOME. `ls` shows this as `'VirtualBox VMs'`, whereas `eza` shows it as `VirtualBox VMs`. I feel the former is useful in quickly identifying (visually) files with special chars in their names. 

Can such an option be added for `eza`?

**Comment by cfxegbert** [comment]
https://github.com/eza-community/eza/pull/20

This is an old pull request from exa.  We should reexamine this pull request.

**Comment by alaymari** [comment]
It would be a real replacement for `ls` if that happens :-)
