### ISSUE TITLE
bug: eza exits successfully when os error 13 occurs

### ISSUE THREAD

**Issue by asahi-m** [eza-community/eza#317]
version: v0.11.1
System: Arch Linux x86_64

eza exits successfully when os error 13 occurs. It should exit with another exit code than 0.

Example steps to reproduce:
```shell
$ eza /root
"/root": Permission denied (os error 13)
$ echo $?
0
```

**Comment by mightbesimon** [comment]
this issue came back again
current version v0.23.4
