### ISSUE TITLE
bug: windows defender labels `eza.exe` v0.12.0 as a trojan (false positive)

### ISSUE THREAD

**Issue by cafkafk** [eza-community/eza#330]
This isn't our first rodeo, and last time microsofts analyst labeled us as neither malware nor an unwanted application.
![2023-09-15_04-59](https://github.com/eza-community/eza/assets/89321978/901d28f6-9e79-4b94-a3a3-60ebf8cb0bf6)

I've submitted the file again for `v0.12.0`, now we just wait...

**Comment by cafkafk** [comment]
@sitiom found that compiling with msvc didn't cause this issue. We should start shipping msvc compiled binaries for windows as well...

**Comment by sitiom** [comment]
Also, the [Winget PR](https://github.com/microsoft/winget-pkgs/pull/119796) can't be merged until the false positive goes away
