### ISSUE TITLE
bug: eza --icons for some reason wouldn't work.

### ISSUE THREAD

**Issue by rexackermann** [eza-community/eza#333]
Flags: eza --icons
System : Fedora (Linux fedora002 6.4.12-200.fc38.x86_64 SMP PREEMPT_DYNAMIC Wed Aug 23 17:46:49 UTC 2023 x86_64 GNU/Linux)
eza version : v0.11.1 [+git]

In my home dir eza --icons will simply freeze.On other directories it seems to work fine.Any idea whats going on ??

**Comment by cfxegbert** [comment]
Can you send a list of file names in your home directory so we can test.
The output of `\ls -1` and `\ls -1 | od -c`

**Comment by rexackermann** [comment]
Okay, I have no idea what caused that but my computer crashed for another reason and after rebooting it now works.
Thanks for the quick reply.I am closing the issue for now.
