### ISSUE TITLE
bug: hidden files are not... hidden

### ISSUE THREAD

**Issue by RaffaeleBianc0** [eza-community/eza#336]
- eza --version = 0.12.0
- The command-line arguments you are using: eza.exe (no arguments needed)
- Your operating system and hardware platform: Windows 11 Pro + Windows Terminal 1.17.11461.0 on HP ZBook Firefly 15 G8 PC

Hello,
hidden files always show up (see "thumbs.db" in the screenshot below).
It seems to me that eza.exe is ignoring the "-a" option, as if it is always active.

![image](https://github.com/eza-community/eza/assets/12746830/153243e4-8514-4b85-b788-e982228fbd5a)

**Comment by cafkafk** [comment]
#225 might be related

**Comment by alamb3142** [comment]
Hi @RaffaeleBianc0 I had PR #225 up to resolve this but there were some issues with `is_ok_and()` not being stable in the minimum supported Rust version, I'll be submitting another PR to work around this later today

**Comment by daviessm** [comment]
> Hi @RaffaeleBianc0 I had PR #225 up to resolve this but there were some issues with `is_ok_and()` not being stable in the minimum supported Rust version, I'll be submitting another PR to work around this later today

MSRV is now 1.70 so you should be good to go with that (#313).

**Comment by cafkafk** [comment]
> Hi @RaffaeleBianc0 I had PR #225 up to resolve this but there were some issues with `is_ok_and()` not being stable in the minimum supported Rust version, I'll be submitting another PR to work around this later today

we also just changed to 1.70 today

**Comment by cafkafk** [comment]
@daviessm beat me to it

**Comment by alamb3142** [comment]
@cafkafk sweet, can I just re-submit my previous change?

**Comment by cafkafk** [comment]
> @cafkafk sweet, can I just re-submit my previous change?

Yeop!

**Comment by alamb3142** [comment]
@cafkafk #343 is up!

**Comment by cafkafk** [comment]
closed by #343, thanks for submitting the PR :heart:
