### ISSUE TITLE
feat:  Add termux package 

### ISSUE THREAD

**Issue by rexackermann** [eza-community/eza#340]
exa had package for termux.So I was wondering if eza is going to have it as well.

**Comment by MartinFillon** [comment]
https://github.com/termux/termux-packages/issues/17681

**Comment by TomJo2000** [comment]
Closed in: [termux/termux-packages#17828](https://github.com/termux/termux-packages/pull/17828).
Should be rolling out to all Termux mirrors within a few hours.
