### ISSUE TITLE
bug: dashes are hardly visible on the dark background

### ISSUE THREAD

**Issue by Solarunit** [eza-community/eza#354]
After exa replacement dashes are hardly visible on the dark terminal background:

![dashes](https://github.com/eza-community/eza/assets/20891064/795f87d8-f418-4b6c-bd04-fd51eac70bd6)

is there way to change  its color?

**Comment by PThorpe92** [comment]
Which version are you currently using? 

This was an issue for quite a few people until we recently upgraded to using Bright terminal colors. [Here](https://github.com/eza-community/eza/issues/240) you can see the thread.
which seemed to fix it for most, so I'm curious if you are running the latest release?

**Comment by okand** [comment]
I was having the same issue and found that eza uses the black colour of your terminal theme for these symbols. I just adjusted mine to be more grey, as you can see to the right in this screenshot. Not sure which of these colours exa used to be honest. Haven't tinkered with them side by side much yet.

![image](https://github.com/eza-community/eza/assets/2211080/bf422533-deb6-4266-affa-db93044e096c)

**Comment by cafkafk** [comment]
> Haven't tinkered with them side by side much yet but it was never a problem in exa.

There is a discussion related to this #194

**Comment by PThorpe92** [comment]
> I was having the same issue and found that eza uses the black colour of your terminal theme

I help maintain the ANSI terminal library we use, and recently we added support for the `Bright` colors. Eza punctuation now (as of v0.1.1) uses what your UI would refer to as Bright Black, however I thought Dark Grey was a much better name :)

**Comment by Solarunit** [comment]
> Which version are you currently using?

eza, version: 0.12.0 + Alacritty with gothem theme

**Comment by holmesrichards** [comment]
Colors can be changed with an environment variable, see `man eza_colors` and `man eza_colors-explanation`. (At least in Linux, do these work in Windows and Mac?) Short version: Put

```export EXA_COLORS="xx=37"```

in `.profile` (or whatever the equivalent is in the shell you use) to make the dashes white for instance (color 37).

**Comment by Solarunit** [comment]
> export EXA_COLORS="xx=37"

I actually was using `EXA_COLORS` to change default bold text to regular one. 
`"xx=37"` - that's what I was looking for yesterday, thanks, it worked!

**Comment by PThorpe92** [comment]
I was hoping that the punctuation issue was solved, but I guess it's impossible to work for every theme. Hopefully with the config file implemented in the 1.0 release will at least make it more idiomatic to change and theme these things. Thanks @holmesrichards 

Closing this as solved for now :+1:
