### ISSUE TITLE
feat: ship rendered manpages as part of release

### ISSUE THREAD

**Issue by tranzystorekk** [eza-community/eza#357]
It would be a welcome convenience for package maintainers to include manpages already rendered to the roff format.

Some ideas for reference:

- gzip manpages and ship as a new release artifact
- create a new source code release artifact that also includes the rendered manpages alongside the markdown templates

**Comment by cafkafk** [comment]
> * gzip manpages and ship as a new release artifact

Easy to do, will do this when I'm not occupied with other stuff. Thought of doing this for a while.

What distro are you packaging for?

**Comment by tranzystorek-io** [comment]
> What distro are you packaging for?

Void Linux, currently working on replacing exa: https://github.com/void-linux/void-packages/pull/45972

**Comment by sevz17** [comment]
> * gzip manpages and ship as a new release artifact
> 

Please don't. Each distro have their own policy respecting compressed man pages/docs.

[This](https://cmpct.info/~sam/blog/posts/automatic-manpage-compression/) entry talks about Gentoo, but it also points out some other distro's preferences.

**Comment by tranzystorek-io** [comment]
@sevz17 I meant more specifically making one .tar.gz archive with manpages inside, not gzipping manpages separately, sorry for the ambiguity

**Comment by sevz17** [comment]
Oh, then it's all right. That was my unique concern.

Thanks for suggesting this!

**Comment by tranzystorekk** [comment]
Seems https://github.com/eza-community/eza/commit/c0df8ecd84380878367845a3c6629fcf4d40fe00 makes this completed 🎉
