### ISSUE TITLE
feat:  Listing files only

### ISSUE THREAD

**Issue by RaWolFoX** [eza-community/eza#367]
Like -D, add option to show files only. Let me know if its already there.

**Comment by cafkafk** [comment]
Could you expand on what `-D` should do? Currently the `-D` flag is taken.

**Comment by RaWolFoX** [comment]
> Could you expand on what `-D` should do? Currently the `-D` flag is taken.

-D Lists folders/dirs. Like that maybe a flag like --files should display only files.
