### ISSUE TITLE
feat: supporting time format strings

### ISSUE THREAD

**Issue by StayPirate** [eza-community/eza#371]
### How to reproduce

versions: `v0.11.1 [+git]`
run: `TIME_STYLE='+%d-%m-%Y %H:%M:%S %z' eza -l`

```bash
> eza -l
eza: Option --time-style has no "+%d-%m-%Y %H:%M:%S %z" setting (choices: default, long-iso, full-iso, iso, relative)
```
### Expected results

Since `eza` is using `TIME_STYLE` env var, I would expect it to handle valid strings as the `ls` command does. 

```bash
> ls -l
total 0
drwxr-xr-x 1 crazybyte crazybyte    0 04-03-2023 19:27:39 +0100 Documents
drwxr-xr-x 1 crazybyte crazybyte 3468 13-09-2023 18:00:05 +0200 Downloads
drwxr-xr-x 1 crazybyte crazybyte   50 11-07-2023 18:26:43 +0200 Games
drwxr-xr-x 1 crazybyte crazybyte  184 07-07-2023 09:38:23 +0200 Workspace
```

See also https://github.com/ogham/exa/issues/923 and https://github.com/ogham/exa/issues/875.

**Comment by PThorpe92** [comment]
We would be happy to accept a PR for this, as it is definitely something that would be nice to support :+1:
