### ISSUE TITLE
feat: Use env vars `EZA_*` (only use `EXA_*` as fallbacks) ?

### ISSUE THREAD

**Issue by bew** [eza-community/eza#374]
It feels weird to use `eza` and configuring its colors using `EXA_COLORS` instead of `EZA_COLORS`.

I think `eza` should get its own set of env vars starting with `EZA_` instead of the old ones (`EXA_`) from the original exa project.

It could still support loading exa' env vars, but the main ones should be for eza now that this is the official successor.

**Comment by cafkafk** [comment]
#110 also exists but I think `v1.0` would be a good time to consider this seriously

**Comment by cafkafk** [comment]
Ohh we probably wont remove the fallback, I don't see any reason to do that if we have them. Also `v1.0` isn't that far in the future.

**Comment by cfxegbert** [comment]
Should we load `EXA_COLORS` first and then load `EZA_COLORS` or only load `EXA_COLORS` if `EZA_COLORS` is unset?

**Comment by cafkafk** [comment]
> Should we load `EXA_COLORS` first and then load `EZA_COLORS` or only load `EXA_COLORS` if `EZA_COLORS` is unset?

IMO, if we load `EZA_COLORS` first, and only load `EXA_COLORS` if `EZA_COLORS` isn't found, it would allow people to have different configs for `exa` and `eza`, at least that was my original view.

But now, I feel like every distro has moved to `eza`, and maybe people would prefer their old config falling through?
Honestly, depends on what users want, I don't use these env vars so I'm not really in tune with what people prefer.

**Comment by bew** [comment]
I'd be on the side of: load `EZA_COLORS` and if not found, load `EXA_COLORS`
