### ISSUE TITLE
feat:  Distinct color for me, other user, root (and same for groups)

### ISSUE THREAD

**Issue by bew** [eza-community/eza#377]
Hello!

Currently we have `uu` & `un` for me and other user (and `gu` & `gn` for groups)

I'd like to color differently the user for:
- my user (`uu`, no change)
- other user that is not root (`un`)
- root (`uR`, which would default to `un` if not set)

And same for groups:
- one of my group (`gu`, no change)
- another group that is not root (`gn`)
- root (`gR`, which would default to `gn` if not set)

---
For example in this screenshot:
![Screenshot_20230918_215552](https://github.com/eza-community/eza/assets/9730330/5f04d1d6-7805-4bf8-ae0f-ac2ce99a3cad)
It's quite hard to see `sddm` in the middle, would be better to have root in something like dark red, so not-me & non-root users stand out.

**Comment by MartinFillon** [comment]
I am going to take a look at that I think it is doable
