### ISSUE TITLE
bug: `--git-repos` should not use colors when `--color=never`

### ISSUE THREAD

**Issue by RuRo** [eza-community/eza#391]
```sh
nix run github:eza-community/eza -- --version
# v0.13.0 [+git]

cd $(mktemp -d)
git init repository
nix run github:eza-community/eza -- --color=never --git-repos --long
```

![Screenshot_20230919_040449](https://github.com/eza-community/eza/assets/3747318/1d99fd57-28a2-4f04-bb59-777b8e9e1a74)

The output of `--git-repos` uses colors even when `--color=never` is set.

**Comment by cafkafk** [comment]
@PThorpe92 would you be available to look into this? Seems like you know this part of the code best.
