### ISSUE TITLE
bug: v0.12.0 releases for windows are v0.13.0 binaries

### ISSUE THREAD

**Issue by Redfire75369** [eza-community/eza#398]
Downloading the binary at <https://github.com/eza-community/eza/releases/download/v0.12.0/eza.exe_x86_64-pc-windows-gnu.zip>, which is expected to be v0.12.0 provides a v0.12.0 binary.

```
> eza.exe --version
eza - A modern, maintained replacement for ls
v0.13.0 [+git]
https://github.com/eza-community/eza
```

This was originally found in https://github.com/microsoft/winget-pkgs/issues/120192.

**Comment by cafkafk** [comment]
Can you test this one out and see if it's `v0.12.0`?
[x86_64-pc-windows-gnu.zip](https://github.com/eza-community/eza/files/12668589/x86_64-pc-windows-gnu.zip)

**Comment by devinherron** [comment]
> Can you test this one out and see if it's `v0.12.0`? [x86_64-pc-windows-gnu.zip](https://github.com/eza-community/eza/files/12668589/x86_64-pc-windows-gnu.zip)
```
❯ ./eza.exe --version
eza - A modern, maintained replacement for ls
v0.12.0 [+git]
https://github.com/eza-community/eza
```

**Comment by cafkafk** [comment]
I'm not sure what's causing this, but `v0.13.0` is already out and I'm not sure we'll have time to fix this right now. If this happens again with another release I'll reopen.
