### ISSUE TITLE
bug: Test and fix all bash completions

### ISSUE THREAD

**Issue by daviessm** [eza-community/eza#400]
Bash completions have been a bit unloved, we should go through and test/fix them.

**Comment by daviessm** [comment]
Save time by removing all completions and use this instead: https://docs.rs/clap_complete/4.4.1/clap_complete/
Depends on #197

**Comment by FilipeBento** [comment]
I'll add that version 0.18.20 added --show-symlinks flag but did not added it to the bash completions file. Version 0.18.21 might have the same issue with the zsh completions.

**Comment by FilipeBento** [comment]
The issue persists in release `0.20.1`. The new options `--follow-symlinks` and `--group-directories-last` were added to --help and auto-complete, but _at least_ `--show-symlinks` and `--no-symlinks` are missing.

**Comment by cafkafk** [comment]
> I believe it is simply a matter of adding all the missing options to `eza --help`. If we do so, they seem to be automatically loaded.

What makes you believe that is the case?  Could you link to a mechanism in native bash that creates this linking?

Also, for what it's worth, creating a contribution that adds flags to the help flag is an easy first contribution for anyone interested.

**Comment by FilipeBento** [comment]
My programming skill is very rusty, but the autocomplete file seems to gather the flags from --help, as shown here:
https://github.com/eza-community/eza/blob/74fed8cefc2625cb75e621ff5aeb9611691d5c0d/completions/bash/eza#L57-L64

Specifically this
```bash
parse_help=$(eza --help | grep -oE ' (--[[:alnum:]@-]+)' | tr -d ' ' | grep -v '\--colo') 
```
