### ISSUE TITLE
feat:  Extended Access Control List

### ISSUE THREAD

**Issue by SteveLauC** [eza-community/eza#403]
```shell
$ ls -l file
-rw-r--r--. 1 steve steve 0 Oct 18 08:07 file

$ setfacl -m g:docker:r file

$ ls -l file
-rw-r--r--+ 1 steve steve 0 Oct 18 08:07 file
```
When a file has Extended ACL or a directory has default ACL, `ls -l` would show a `+` at the end of the permission string. This is the behavior of GNU `ls`, and seems that [`ls` on macOS also supports this feature.](https://apple.stackexchange.com/q/26776/394687)

ref: [exa#1137](https://github.com/ogham/exa/issues/1137)

**Comment by cfxegbert** [comment]
Also ref: https://github.com/eza-community/eza/issues/292

**Comment by SteveLauC** [comment]
These two issues are basically the same, sorry for opening a duplicate issue.
