### ISSUE TITLE
bug: Some icons not diplayed

### ISSUE THREAD

**Issue by simonspa** [eza-community/eza#409]
I am running `eza` in the `fish` shell and I'm having some trouble with the `--icons` option. Specifically, some special folder-name icons are not rendered:

![image](https://github.com/eza-community/eza/assets/1677436/2c51e46c-d9d6-4640-826f-5c763be0c363)

This is on `eza v0.13.0 [+git]` and `fish, version 3.6.1`.

Is there any other information I can provide to help tracking this down?

**Comment by PThorpe92** [comment]
Can you let us know what version of Nerd Fonts you are using? This is a common problem with people using fonts that are still using Nerd Fonts 2. If you look into patching your font or upgrading to one using version 3, it's likely that will fix the issue :+1:

**Comment by simonspa** [comment]
Wow, thank you so much @PThorpe92, that very swiftly solved my issue. I was using [Meslo NF as linked on the Tide repo](https://github.com/IlanCosman/tide#fonts) which turns out to be quite out-of-date.

Updating to the [latest version provided by powerlevel10k](https://github.com/romkatv/powerlevel10k-media/) solves the issue. :tada: 

I shall file a pull request for Tide. :)
