### ISSUE TITLE
feat:  Support a full path listing option when using --tree output 

### ISSUE THREAD

**Issue by fidgetingbits** [eza-community/eza#416]
First just one to say thanks for forking exa and trying to maintain it!

This is just me mirroring the original exa request posted here https://github.com/ogham/exa/issues/754. I'd like to move to using `eza --tree` to replace my use of `tree`, since the `tree` utility doesn't support honoring `.gitignore`, etc. However, I regularly rely on the `tree -f` option to be able to easily access the full path of the underlying files after I find what I need. 

For context:

```
❯ tree --help
usage: tree [-acdfghilnpqrstuvxACDFJQNSUX] [-L level [-R]] [-H  baseHREF]
        [-T title] [-o filename] [-P pattern] [-I pattern] [--gitignore]
        [--gitfile[=]file] [--matchdirs] [--metafirst] [--ignore-case]
        [--nolinks] [--hintro[=]file] [--houtro[=]file] [--inodes] [--device]
        [--sort[=]<name>] [--dirsfirst] [--filesfirst] [--filelimit #] [--si]
        [--du] [--prune] [--charset[=]X] [--timefmt[=]format] [--fromfile]
        [--fromtabfile] [--fflinks] [--info] [--infofile[=]file] [--noreport]
        [--version] [--help] [--] [directory ...]
  ------- Listing options -------
  -a            All files are listed.
  -d            List directories only.
  -l            Follow symbolic links like directories.
  -f            Print the full path prefix for each file.
```

Usage output:

```
❯ tree -f foo
foo
├── foo/a
└── foo/bar
    ├── foo/bar/b
    └── foo/bar/bas
        ├── foo/bar/bas/baz
        │   └── foo/bar/bas/baz/d
        └── foo/bar/bas/c

4 directories, 4 files
```

**Comment by ariasuni** [comment]
If we display the absolute path, I believe the tree may be redundant, and we could format the output like so:

```
foo
foo/a
foo/bar
foo/bar/b
foo/bar/bas
foo/bar/bas/baz
foo/bar/bas/baz/d
foo/bar/bas/c
```

It would avoid very long lines and with the color I believe it could be quite readable.

**Comment by fidgetingbits** [comment]
That also seems reasonable to me

**Comment by cafkafk** [comment]
this reminds me very much of `fd`, should we even do this when fd already exists?

**Comment by fidgetingbits** [comment]
Ah right that's exactly what `fd` does and it also honors `.gitignore`. I can just live with using that instead then. I've been trying to think about some case where having the actual tree visualization helps, but after driving `fd` for a bunch today I can't think of anything. Happy to just close this then, unless someone thinks of some other benefit.

**Comment by MartinFillon** [comment]
Well I am closing this but if anyone want to talk about this we can just reopen it

**Comment by cafkafk** [comment]
@MartinFillon you can also set it as not planned for now, that makes it feel more like we're not doing it immediately, but makes it easier to search for later if we ever run out (probably wont but you know)

**Comment by MartinFillon** [comment]
We don't have a not planned tag
