### ISSUE TITLE
feat: option to add a space after the icon

### ISSUE THREAD

**Issue by asininemonkey** [eza-community/eza#418]
Firstly, a big thank you for this project. It's made my terminal so much nicer to use.

With regards my request, the OCD in me has an issue with the icon being right next to the listing with no spacing. The ability to configure this (unless I'm overlooking some other setting) would be much appreciated.

**Comment by MartinFillon** [comment]
As of my run of the eza command there seem to already be a space between the icon and the filename, can you precise what you are running in term of distribution, eza version, command, result of the command.

**Comment by piechologist** [comment]
Set the environment variable `EXA_ICON_SPACING=2`. It's at the bottom of the man page.
