### ISSUE TITLE
feat: BSD native support

### ISSUE THREAD

**Issue by axeld-galadrim** [eza-community/eza#423]
Hello!
I looked at the different ways to install `eza`, and there are actually quite a lot!
Tho, I saw that FreeBSD and OpenBSD and some other BSD were missing!
I think that letting people add eza using `pkg_add` will be a good way to 
1) Make eza used by more people
2) Add even more features than exa (which, to my knowledge, isnt available in the repos of FreeBSD and OpenBSD)

- [X] OpenBSD
- [X] FreeBSD
- [X] NetBSD
- [ ] DragonflyBSD

**Comment by cafkafk** [comment]
I mean, we juts need a BSD person to do that really.

**Comment by axeld-galadrim** [comment]
Oh ok, but does this person need to be part of the eza community or something, or could it be anyone ?
I might know someone that can do it.
Thanks for your quick answer!

**Comment by cafkafk** [comment]
I mean it could be anyone, but they'd also have maintain it. Of course, I don't know exactly what it would require to support BSD.

**Comment by axeld-galadrim** [comment]
Right! Thanks for your return
A bit off-topic: but thanks a lot for `eza`! I really like the devotion that you put in it with all the `eza-community`, so thank you!

**Comment by koutheir** [comment]
Installing `eza` works through `cargo install eza` on FreeBSD 13.2. `eza` itself also seems to work properly.

**Comment by cafkafk** [comment]
you likely didn't get completions and manual pages thou I imagine, so there's definitely still a use for someone packaging it

**Comment by koutheir** [comment]
> you likely didn't get completions and manual pages thou I imagine

- No completions. I didn't fetch `completions/` from the repository. I'm using the `fish` shell.
- No manual pages, but `eza --help` works.

> so there's definitely still a use for someone packaging it (but i'm glad to hear it works on freebsd in the first place)

I agree.

**Comment by koutheir** [comment]
I never packaged anything on FreeBSD, but I'm interested in implementing features that are missing on FreeBSD. Does anybody know of such features?

I only know of security contexts, but these are Linux-specific because SELinux is only implemented there.

**Comment by VlkrS** [comment]
`eza` was just added to the OpenBSD ports tree.

`exa` is available in the ports trees of both OpenBSD and FreeBSD, so if you are interested in making `eza` available on FreeBSD, maybe get in touch with the `exa` maintainer:

https://www.freshports.org/sysutils/exa/

**Comment by axeld-galadrim** [comment]
Really nice for OpenBSD. Happy to hear that. Congrats!

**Comment by axeld-galadrim** [comment]
For people that don't have OpenBSD installed but want to check the status of `eza` on OpenBSD, you can use https://openbsd.app to search for package. For [eza](https://openbsd.app/?search=eza&current=on)

**Comment by kdeguchi** [comment]
I have added eza to the FreeBSD ports tree. Thank you.

https://www.freshports.org/sysutils/eza/

**Comment by yonas** [comment]
> I have added eza to the FreeBSD ports tree. Thank you.
> 
> https://www.freshports.org/sysutils/eza/

@axeld-galadrim Recommend close this issue.

**Comment by axeld-galadrim** [comment]
@yonas as far as I know, NetBSD and dragonflyBSD which are 2 populars BSD are still missing.

**Comment by yonas** [comment]
@axeld-galadrim You're right :+1:

**Comment by axeld-galadrim** [comment]
Noted NetBSD as done:
http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/sysutils/eza/?only_with_tag=MAIN

**Comment by VlkrS** [comment]
I'm not a Dragonfly User, but afaict, it will eventually pick up the port from FreeBSD:

https://www.dragonflybsd.org/docs/howtos/HowToDPorts/

**Comment by axeld-galadrim** [comment]
Right! @cafkafk are you ok to close this issue than ?

**Comment by cafkafk** [comment]
> Right! @cafkafk are you ok to close this issue than ?

Well, I guess we've gotten em all then! :tada:

**Comment by axeld-galadrim** [comment]
XD
BSDs, gotta catch 'em all!
(In reality, there are some other obscures BSDs out there, but the more popular ones are done)
