### ISSUE TITLE
bug: Output in v0.13.0-1 not parseable in Bash like it was in v0.13.1-1

### ISSUE THREAD

**Issue by quickishfm** [eza-community/eza#428]
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`)
- The command-line arguments you are using
- Your operating system and hardware platform

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---
I'm using Arch Linux 6.5.4-arch2-1 with latest Eza from the Pacman repo (v0.13.1-1)

In previous version of eza in the Arch repo, I can list the newest file in a folder by doing

`ls -sold | head -1`

With v0.13.1-1 though, the output shows ALL the files, in the right order, but the output can not be delimited with `head` anymore

e.g., what I expect to see
```
$ ls
a  b  c  d  e
$ ls -sold | head -1
e
```

What I actually see
```
$ ls
a  b  c  d  e
$ ls -sold | head -1
e  d  c  b  a
```

**Comment by ariasuni** [comment]
I’m not sure why the change of behavior, but isn’t `-1`/`--oneline` what you should be using?

**Comment by quickishfm** [comment]
That does actually do the trick, thanks. It seems when I have many files, it displays them multiple files per line, and multiple lines, and then piping that (without `-1`) to `head` results in that top line (which still has a few files) being output. Using `-1` from now on works for me, so shall I still leave this open? I'd ideally like to see the original behaviour restored too but I feel it's more of a personal preference, even if it does invalidate existing workflows that rely on that previous behaviour.

**Comment by ariasuni** [comment]
Well, I think eza is supposed to show one file per line when piped and you don’t pass any display option, so yeah let’s keep that open

**Comment by quickishfm** [comment]
It also now seems to output color information by default when piped, leading to some weird behaviour until I append "--colour=never" to the output. This breaks several scripts I have in place too, so having this fixed would be great.

**Comment by daviessm** [comment]
@quickishfm Can you try the branch from #438 and see if it fixes the problem for you?

**Comment by quickishfm** [comment]
Thanks @daviessm, pulling from https://github.com/hehelego/eza (main branch) and then building with `cargo build`, that version of `eza` works great for me - I don't see the multiple-files-on-one-line issue I raised this bug for, and as a bonus, the color information is also omitted when piping, which (in total) fixes all of the issues I was having.
