### ISSUE TITLE
bug: `--color=automatic` dose not work

### ISSUE THREAD

**Issue by hehelego** [eza-community/eza#433]
When piping output of `eza` to another program or simply redirecting stdout to  another file, color controll characters present in the output. The expected behavior is that colorization is disabled when `eza` detect that it is not printing things to pty/tty. 

To reproduce:

```fish
eza --color=automatic --online | fzf
eza --color=automatic --online > eza-out; cat ./eza-out
```

You can see things like `[1;34mvar[0m`.

In contrast, when using coreutils ls, no color should be there.

- The version of eza being used (`eza --version`): `v0.13.1 [+git]`
- The command-line arguments you are using: `eza --color=automatic --oneline`
- Your operating system and hardware platform: `Arch Linux, x86_64`
- This bug is reproduced on a clean container using the `docker.io/ubuntu:latest` image, so it is not my env/config file causing the problem.

**Comment by cafkafk** [comment]
As you can observe from e.g. the fish comletions:
```
✦ ❯ eza --color=always 
--color=always  (Always use colour)  --color=auto  (Use colour if standard output is a terminal)  --color=never  (Never use colour)
```
It uses color if standard output is a terminal, making this expected behavior.

**Comment by hehelego** [comment]
Interesting, I rember that `exa`  handle colorizaton diifferently.
I'll make it a feature request.

**Comment by cafkafk** [comment]
> Interesting, I rember that `exa` handle colorizaton diifferently. I'll make it a feature request.

Okay!
