### ISSUE TITLE
feat: Do not colorize the output when stdout is not connected to a real terminal when `--color=auto` or `--color=automatic`  is set.

### ISSUE THREAD

**Issue by hehelego** [eza-community/eza#434]
coreutils `ls` and [exa](https://github.com/ogham/exa) has a `--color=auto` option that disables colorization when the output is redirected or piped.  
This is very helpful when you want to combine `eza` with other CLI/TUI tools. I am listing a few use cases

- `eza --color=auto --online *.py| fzf` to make a fuzzy search on the `eza` output.
- `eza --color=auto | rg SOMEFANCYREGEX` to do subsequent search in the result.
- `eza --color=auto | nvim -` to edit the output manually. 
- `eza > eza-ouput` to save the output as a text file.

In these cases, you don't want the ANSI controll characters to be included. 

`ls --color=auto` dose exactly the thing we want. Since `eza` is intended to be a replacement of  `ls`, we should support similar functionality.

----

Relavent issue: https://github.com/eza-community/eza/issues/433

**Comment by hehelego** [comment]
Well, I think that is change in `terminal_size` causing this problem.  

Previsouly the `terminal_size::terminal_size()` function is simply `terminal_size_using_fd()` on `stdout`, which is what we need here.
Later on, it is changed to query `terminal_size_using_fd()` on `stdout, stderr, stdin`.  
The commit that did this is: https://github.com/eminence/terminal-size/commit/08f0e73926c11adc3105dbf4eb84dd8c9e6c873a

To correct the behavior, we should query `terminal_size_using_fd()` on `libc::STDOUT_FIILENO`.

**Comment by PThorpe92** [comment]
Thanks! I assigned this to you so nobody else jumps on it, just let me know if you change your mind or don't have time for it:+1:

**Comment by hehelego** [comment]
PR created at https://github.com/eza-community/eza/pull/438

**Comment by hehelego** [comment]
> Thanks! I assigned this to you so nobody else jumps on it, just let me know if you change your mind or don't have time for it👍

Actually, I went for dinner and had a nap 🫠. Later on, I realized that my patch haven't been pushed.
