### ISSUE TITLE
bug: Missing icon for YAML files

### ISSUE THREAD

**Issue by Teraskull** [eza-community/eza#436]
![image](https://github.com/eza-community/eza/assets/24798198/3ba04ac5-c1b8-4685-a7fe-450c15923b62)

Windows 11
eza v0.13.1

```powershell
eza -Fahl --group-directories-first --sort extension --octal-permissions --icons
```

**Comment by PThorpe92** [comment]
![image](https://github.com/eza-community/eza/assets/121899304/10b915ae-36b9-407f-8084-6e85adc6c383)

Well at first I i definitely thought there was an issue until..

![image](https://github.com/eza-community/eza/assets/121899304/502b189b-6122-4a92-af18-845ec32c9577)
Screenshot from [nerd fonts cheat sheet](https://www.nerdfonts.com/cheat-sheet)

Does your font support Nerd Fonts 3?

Another issue would definitely be.. why is the `!` a .yml icon?

**Comment by Teraskull** [comment]
Oh, that's what it is, I'm still using FiraCode Nerd Fonts 2.1.0, thanks!
