### ISSUE TITLE
bug: eza.rocks rendering error

### ISSUE THREAD

**Issue by dimitrilw** [eza-community/eza#447]
I apologize in advance if this is the wrong place for reports re the [eza.rocks](https://eza.rocks/) website.

Basically, the expanded sections are not rendered properly. See screenshot, below. It appears that the markdown-to-html conversion is not processing all content.

---

<img width="956" alt="image" src="https://github.com/eza-community/eza/assets/5898931/ccb81354-d151-4532-9242-039413ceb93f">

**Comment by dimitrilw** [comment]
I should have included:
I was viewing the site via Chrome browser, Version 117.0.5938.132; current version as of the time of this post.

I do not believe that info is relevant, as it clearly appears to be a pre-processing issue, not a browser issue. But deets matter. 😄

**Comment by Cyborus04** [comment]
There is a repo for the website ([here](https://github.com/eza-community/eza.rocks)), that seems like the best place for this issue

**Comment by dimitrilw** [comment]
I'll close this issue & repost there. Cheers!
