### ISSUE TITLE
bug: icons are not displayed

### ISSUE THREAD

**Issue by dimitrilw** [eza-community/eza#448]
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`) = v0.13.1 [+git], installed via Homebrew
- The command-line arguments you are using = `-hl --icons` or just `--icons`
- Your operating system and hardware platform = Apple Silicon, MacOS Sonoma 14.0 (current as of this post)

Images show that padding is added for icons, but no icons displayed. Are there special instructions for installing fonts? I did not see additional instructions in the readme. Also, I have many nerd fonts already installed.

---

<img width="673" alt="image" src="https://github.com/eza-community/eza/assets/5898931/e62a4c28-0f9a-4cfc-a965-cef601000898">

<img width="528" alt="image" src="https://github.com/eza-community/eza/assets/5898931/4541ee58-1b17-453e-9254-ac5b813179dd">

**Comment by gierens** [comment]
Which version of Nerd Fonts are you using? ... A common problem is that people still use version 2 which doesn't have all the symbols. Updating to version 3 should likely fixes the issue.

**Comment by dimitrilw** [comment]
So, I forgot to come back and close this. I apologize. While fiddling around trying to resolve, I figured out that my terminal app was no longer using the nerd-font I'd previously selected. Didn't even notice the change. Anyway, that's the issue. Sorry for not closing this ticket promptly. 😊
