### ISSUE TITLE
feat: Allow changing color of git-repos symbols  

### ISSUE THREAD

**Issue by holmesrichards** [eza-community/eza#450]
Looking at ui_styles.rs, it appears to lack provision for changing the --git-repos columns colors.

(Bold yellow is virtually unreadable with the light background I use; I've changed it to orange where I can:)
![image](https://github.com/eza-community/eza/assets/56895621/74d3d0b9-f87b-41f7-ab2a-8763e697ed27)

**Comment by MartinFillon** [comment]
Gonna take a look into that
