### ISSUE TITLE
bug: static version with -l flag will segfault

### ISSUE THREAD

**Issue by laoshaw** [eza-community/eza#466]
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`)
v0.13.1 
- The command-line arguments you are using
-l
- Your operating system and hardware platform
ubuntu 22.04 x86

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---

if I use the static version, [eza_x86_64-unknown-linux-gnu_static.tar.gz](https://github.com/eza-community/eza/releases/download/v0.14.0/eza_x86_64-unknown-linux-gnu_static.tar.gz), when '-l' option is used, it segfaults.

**Comment by PThorpe92** [comment]
![image](https://github.com/eza-community/eza/assets/121899304/6c3d68f1-bcee-43c7-92db-2d754428e64c)
Indeed it does...

Thank you for reporting this.

**Comment by gierens** [comment]
I think we should first confirm this still happens with v0.14.0 before investigating further.

**Comment by gierens** [comment]
Just tried this with v0.14.0 (https://github.com/eza-community/eza/releases/download/v0.14.0/eza_x86_64-unknown-linux-gnu_static.tar.gz) and there it seems to be working just fine.

**Comment by gierens** [comment]
Confirmed ... getting the same with v0.14.0:

![Screenshot from 2023-10-02 23-28-53](https://github.com/eza-community/eza/assets/49617392/6ed6e313-f004-4b9c-b6f7-084a46a4c637)

**Comment by gierens** [comment]
According to valgrind there seems to be some uninitialized syscall parameter ... for more info we probably need a debug build to track this down.

**Comment by gierens** [comment]
@laoshaw ... quick fix for you ... use the static musl builds like: https://github.com/eza-community/eza/releases/download/v0.14.0/eza_x86_64-unknown-linux-musl.tar.gz

Also since you are on Ubuntu ... you can install eza from the deb repo mentioned in the README.

**Comment by MartinFillon** [comment]
Okay so according to valgrind it seems like our parallelisation usage is not well supported when using static libs

**Comment by MartinFillon** [comment]
Isuue is known in rust please don't use statically linked binaries https://github.com/rust-lang/rust/issues/94564
