### ISSUE TITLE
feat: ship manpages/completions on release

### ISSUE THREAD

**Issue by cafkafk** [eza-community/eza#471]
as the title suggests, I'll have to do this

**Comment by MartinFillon** [comment]
Could you maybe ship the completions ?

**Comment by zw963** [comment]
As a command line tools, if not follow with man help and completions, feels wired ...

anyway, used to use `man exa` for a long time, and have to copy the completion manually from project after download binary.

**Comment by pepoluan** [comment]
I'm looking forward to man pages being released to accompany the standalone binaries in Releases.

The situation is that I'm deploying eza on RHEL 8 systems. There are no eza .rpm packages for RHEL 8, so I have to use the standalone binaries. But that means I don't get the man pages.

Having to install `pandoc` _just_ to convert the markdown help files into man pages is just not palatable for me.

**Comment by cafkafk** [comment]
I've finally found the time to add this to the release script, now we ship completions and man pages as tarballs with the release :3

**Comment by CouldBeThis** [comment]
Maybe if there is work to be done to get the proper man page, in the meantime, a link to https://github.com/eza-community/eza/blob/main/man/eza.1.md could be added to

- this repo's `readme.md`
- `--help` output
- eza.rocks website

@zw963 one thing that's nice about changing name is that calling the `man` page should work consistently. On my systems `man exa` would bring up [`exa(4)](https://www.mankier.com/4/exa) by default. Had to do some configuration to bring the docs for this package. Either that wasn't consistent across systems or you set it up and forgot.
