### ISSUE TITLE
feat: Add option to only show group if it has a different name from owner.

### ISSUE THREAD

**Issue by sebastiancarlos** [eza-community/eza#480]
Just a small suggestion here.

Current:
```
$ eza -l -g
.rw-r--r-- 0 user user  4 Oct 11:58 one
.rw-r--r-- 0 user user  4 Oct 11:58 two
.rw-r--r-- 0 user http  4 Oct 11:58 wow
```

Suggested:
```
$ eza -l -g --smart-group
.rw-r--r-- 0 user :     4 Oct 11:58 one
.rw-r--r-- 0 user :     4 Oct 11:58 two
.rw-r--r-- 0 user http  4 Oct 11:58 wow
```

The idea is to highlight the rare cases in which the group and owner are different.

The `:` character is used as it has similar semantics to the `chown` command, in which the group name is set to be the same as the user name:

```
$ chown user:user file
```

is the same as:

```
$ chown user: file
```

Thanks for your time.

**Comment by cafkafk** [comment]
I like the argument for doing this and if anyone wanna have a go at a PR for this feel free to

**Comment by MartinFillon** [comment]
this is a #379 duplicate

**Comment by cafkafk** [comment]
> this is a #379 duplicate

Hmm, I personally prefer this one's argument for using `:`, I'll close the other for now.

**Comment by cafkafk** [comment]
Implemented in https://github.com/eza-community/eza/pull/514

**Comment by liketurbo** [comment]
> I noticed that `--smart-group` only works if `--group` is also enabled used (which is not by default).
> 
> I propose the two following solutions:
> 
>     1. If the user enable `--smart-group` he'll be advised that he also has to add `--group`
> 
>     2. `--smart-group` implies `--group` enabled even if it's not specified
> 
> 
> TBH I prefer the second solution because IMHO if an user enables `--smart-group` he expects the flag to work, regardless if `--group` is enabled or not.
> 
> Update: I moved this question in a [more appropriate place](https://github.com/orgs/eza-community/discussions/544).

It sounds reasonable, but yet again, `--group` only works with the `--long` option, and there is no auto implication or warning afaik

**Comment by StayPirate** [comment]
I agree with you. Please lets continue this discussion at https://github.com/orgs/eza-community/discussions/544.
