### ISSUE TITLE
bug: Undocumented options

### ISSUE THREAD

**Issue by holmesrichards** [eza-community/eza#488]
- The version of eza being used (`eza --version`)

v0.14.0 [+git]

- The command-line arguments you are using

`-?`

- Your operating system and hardware platform

Linux Mint 21.2

---

The following options are not documented in the man file:

`-?`, `--help`
`-v`, `--version`

The following options are not documented in either the man file or the `--help` output:

`-A`, `--almost-all`
`-X`, `--dereference`

**Comment by cafkafk** [comment]
> -?

We do want to phase this one out before v1.0, and replace it with -h. The others should definitely be documented thou
