### ISSUE TITLE
bug: root group is not highlighted for root user

### ISSUE THREAD

**Issue by Ultimator14** [eza-community/eza#494]
Usually, if a user has a primary group, both the username and the group are highlighted. Since the last version this is no longer the case for the root user.

Normal user:
![Bildschirmfoto vom 2023-10-08 00-16-06](https://github.com/eza-community/eza/assets/30043959/82c0be92-ea2a-4498-b262-9488c9a0a853)

Root user:
![Bildschirmfoto vom 2023-10-08 00-16-15](https://github.com/eza-community/eza/assets/30043959/1e476e01-fbaf-4dc2-aa54-bc1e4c3f0229)

I suspect this is due to the `Separated root color from other users` change and that the color priority of 'group belongs to root' takes precedence over 'group belongs to current user'. But with the default config, this breaks the highlighting of the root group for the root user.

Feel free to close if this was intentional.

OS: Gentoo Linux
Eza: v0.14.0 [+git]

**Comment by cafkafk** [comment]
Refs: #431

**Comment by cafkafk** [comment]
@MartinFillon this is expected right?

**Comment by bew** [comment]
Ah that's an interesting case, as the person who requested this feature in the first place I'm not sure what to do in this case 🤔

**Comment by MartinFillon** [comment]
This is indeed a bug gonna have a look @cafkafk thanks for the heads up @bew
