### ISSUE TITLE
feat:  Add environmental variable for git support. 

### ISSUE THREAD

**Issue by social-anthrax** [eza-community/eza#495]
This is a very niche use-case, but I've currently got a project which causes perceptible lag whenever eza is run with the --git option. I've reverted to using direnv to disable the flag in a wrapper function to make it usable, but it would be nice if we can override flags using environmental variables.

# Issue example
## Time with `--git` 
<img width="437" alt="Screenshot 2023-10-07 at 20 44 57" src="https://github.com/eza-community/eza/assets/40488664/6076c0a6-7f2d-4552-91d2-eed235bf538f">

## Time without `--git`
<img width="397" alt="Screenshot 2023-10-07 at 20 48 52" src="https://github.com/eza-community/eza/assets/40488664/6c6c20fc-9ca8-44c0-8150-b4b841bb5a60">

**Comment by MartinFillon** [comment]
You can also use the `--no-git` option which overrides `--git`, so that it does not break your alias if you have one

**Comment by cafkafk** [comment]
(I think it is an interesting issue imo let's keep it open for now)

**Comment by MartinFillon** [comment]
I am going to work on it I think
