### ISSUE TITLE
bug: spacing issues with hyperlink

### ISSUE THREAD

**Issue by Scartiloffista** [eza-community/eza#515]
seems that the `--hyperlink` feature has some spacing issues
![Screenshot 2023-10-11 at 15 54 06](https://github.com/eza-community/eza/assets/36407154/92d9d7fb-5138-4244-b245-fc68c8ae8cc7)

**Comment by Equationzhao** [comment]
looks like it's caused by the `'`.

**Comment by cafkafk** [comment]
Can confirm this

**Comment by MartinFillon** [comment]
This looks like a mac issue there is a duplicate of this in #543

**Comment by holmesrichards** [comment]
This is about hyperlinks not being displayed correctly, #543 is about hyperlinks not working.

**Comment by MartinFillon** [comment]
Yeah I saw but I think that both are linked

**Comment by Scartiloffista** [comment]
in 0.15.1 the bug seems fixed, at least for me

**Comment by cafkafk** [comment]
Closing as solved then, if anyone else hits this on 0.15.1 or after we can reopen.
