### ISSUE TITLE
bug: invalid argument in zsh completion 

### ISSUE THREAD

**Issue by ChangqingW** [eza-community/eza#522]
I am getting `_arguments:comparguments:325: invalid argument: (- *){--help}[Show list of command-line options]` when trying to use tab completion for eza, either removing the line 
https://github.com/eza-community/eza/blob/4b94b3fb706e6bde523addc6672b1025315ed7a4/completions/zsh/_eza#L14
or editing it to `"(- *)"--help"[Show list of command-line options]" \`seems to resolve the error.

Versions
```
eza --version
v0.14.1 [+git]
https://github.com/eza-community/eza

zsh --version
zsh 5.8.1 (x86_64-pc-linux-gnu)
```
On CentOS Linux 7

**Comment by cafkafk** [comment]
I'll take a look, one moment
