### ISSUE TITLE
bug: Size displayed for symlink is size of target

### ISSUE THREAD

**Issue by holmesrichards** [eza-community/eza#530]
- The version of eza being used (`eza --version`)

v0.14.1 [+git]

- The command-line arguments you are using

eza -l

- Your operating system and hardware platform

Linux Mint 21.2

---

When using `ls -l`, symlink sizes are shown as a few bytes, presumably the actual size of the symlink file:

```
$ ls -l
total 4
lrwxrwxrwx 1 rsholmes rsholmes  23 Oct 14 21:32 xlink.x -> /home/rsholmes/test/x.x
-rw-rw-r-- 1 rsholmes rsholmes 854 Sep 16 11:13 x.x
```

But `eza -l` displays as the size for the symlink the size of the target, while displaying the symlink's permissions and timestamp:

```
$ eza -l
.rw-rw-r-- 854 rsholmes 16 Sep 11:13 x.x
lrwxrwxrwx 854 rsholmes 14 Oct 21:32 xlink.x -> /home/rsholmes/test/x.x
```

`eza -lX` does the same, while the permissions and timestamp change to the target's:

```
$ eza -lX
.rw-rw-r-- 854 rsholmes 16 Sep 11:13 x.x
lrw-rw-r-- 854 rsholmes 16 Sep 11:13 xlink.x -> /home/rsholmes/test/x.x
```

My expectation was that `eza -l` would display the same size as `ls -l` does, and that `eza -lX` would display the target size.

**Comment by cafkafk** [comment]
Ohh, that might be what was the issue in #112
