### ISSUE TITLE
docs: add to readme, man pages, and completions

### ISSUE THREAD

**Issue by Xemptuous** [eza-community/eza#535]
This seems to need to be added to man pages, completions, and the README.md. Can't wait to see this feature in eza, looks very cool.

_Originally posted by @cafkafk in https://github.com/eza-community/eza/pull/533#pullrequestreview-1679797638_

**Comment by PThorpe92** [comment]
That's something you can just include in your PR. Any new features need to come with documentation, completions, manpage, etc. sometimes in a separate commit but in the same PR :+1:
