### ISSUE TITLE
bug: brew install eza error

### ISSUE THREAD

**Issue by TanGuangZhi** [eza-community/eza#538]
No available formula with the name "eza". Did you mean exa or eva?

Homebrew 3.6.5
Macos 11

<img width="761" alt="image" src="https://github.com/eza-community/eza/assets/53848822/2d6bfb56-039f-4c33-8b58-09293d2d421a">

**Comment by cafkafk** [comment]
This should be opened in homebrew https://github.com/Homebrew/homebrew-core
