### ISSUE TITLE
bug: output format unexpectedly becomes one line when used with specific flags

### ISSUE THREAD

**Issue by wytsai7660** [eza-community/eza#549]
- Eza version: v0.15.0 [+git] (installed via homebrew)

- Command-line arguments:
  ```
  eza -x --group-directories-first --icons -a
  ```

- OS:  MacOS Sonoma 14.0 23A344 arm64
---
Problem:

I tested it in different folders. It seems the issue only occurs when coontaining long-name files or folders. Also, sometimes just a single `-x` can reproduce this issue; sometimes I need to use the full `-x --group-directories-first --icons` to reproduce this issue.

used without `-x`
<img width="922" alt="Screenshot 2023-10-20 at 7 01 42 PM" src="https://github.com/eza-community/eza/assets/116703995/67d00ea4-4d29-4bbd-94cd-303cec7370a9">

used with `-x`
<img width="922" alt="Screenshot 2023-10-20 at 7 02 08 PM" src="https://github.com/eza-community/eza/assets/116703995/e6e11945-3ff1-498b-b344-c2607e83d8af">

BTW this is my first issue :wave: Sorry if the format is incorrect; it is totally ok to correct me.

**Comment by PThorpe92** [comment]
I noticed this testing another PR today, there did seem to be some inconsistencies. I'm going to try to narrow down what is causing this.

**Comment by holmesrichards** [comment]
I'm curious what output  you expected, given there isn't room for two columns each the width of the long file names.

**Comment by wytsai7660** [comment]
> I'm curious what output you expected, given there isn't room for two columns each the width of the long file names.

Oh, I see... I misunderstood its output logic. Thanks for your explanation 🙏.

**Comment by PThorpe92** [comment]
> I'm curious what output you expected, given there isn't room for two columns each the width of the long file names.

Indeed this was my first thought was well.. but I think moving to the new dependency for `term_grid` may have perhaps adjusted the width enough where previously there might have been two columns where now there will only show one. 

I dont think this is necessarily a bad thing, because there definitely have been bugs due to trying to squeeze output into too narrow of columns. I think this can be closed tho
