### ISSUE TITLE
feat:  Add icon for `.gql` and `.graphql` extensions

### ISSUE THREAD

**Issue by rew1nter** [eza-community/eza#552]

**Comment by PThorpe92** [comment]
happy to accept a PR :+1: 

adding icons are pretty straight forward

**Comment by rew1nter** [comment]
😅 I don't write rust nor do I know how a GitHub PR works properly

**Comment by PThorpe92** [comment]
very little rust is actually needed (a few lines at most) and there is a whole [page](https://github.com/eza-community/eza/blob/main/src/output/icons.rs) of them to learn from so u can pretty much just copy it. 

Happy to help you through it if you'd like to make ur first PR! 

either way, no worries i'm sure someone will pick it up. :D

**Comment by wllfaria** [comment]
Hey! I'm interested in adding this to the repo... I saw there is a PR already opened with changes that addresses this (#490) but the last interaction there were in november last year.

Is it still viable to add this as a separate PR that addresses just these two icons?

**Comment by cafkafk** [comment]
> Hey! I'm interested in adding this to the repo... I saw there is a PR already opened with changes that addresses this (#490) but the last interaction there were in november last year.
> 
> Is it still viable to add this as a separate PR that addresses just these two icons?

Yes absolutely

**Comment by wllfaria** [comment]
Thanks, i just created a PR, feel free to ask for any changes if needed
