### ISSUE TITLE
Can I get the exa icons back?

### ISSUE THREAD

**Issue by rew1nter** [eza-community/eza#553]
![image](https://github.com/eza-community/eza/assets/64508791/3c8b2961-ceaf-4f9b-9e6a-a7b894a79ab8)
Is it possible to make (at least the folder) icons look like exa?

**Comment by PThorpe92** [comment]
Eza uses those particular icons for empty folders now. There isn't a way (yet) to select individual icons, however when #139 is eventually implemented there might be a way

**Comment by rew1nter** [comment]
Any ETA for that?
I'll stick with exa until then

**Comment by PThorpe92** [comment]
It's hard to say. This is a feature that, along with migration to `Clap` for argument parsing, we intend on releasing with version 1.0 Lots of progress has been made so I don't think its terribly far off. I would say probably before the end of the year, but I also can't speak for all the maintainers.

Lots of work has been put into all the new custom icons as well as the file type classification, but at the end of the day it's definitely matter of preference. Hopefully soon it will be easier to customize :+1:
