### ISSUE TITLE
bug: eza used as a library has no (documented) method to print file paths with formatting

### ISSUE THREAD

**Issue by REALERvolker1** [eza-community/eza#557]
eza version: `eza = "0.15.0"`

I am trying to use eza as a library in my program to print file paths as formatting. According to the crate [documentation](https://docs.rs/eza/0.15.0), it does not have a usable method/function to format strings.

Am I missing something here?

**Comment by cafkafk** [comment]
It's not really meant to be used as a library, we just need a lib.rs in src to be able to use criterion :s

**Comment by cafkafk** [comment]
Essentially, this is not something we currently support, so there's not any further actions to take here. Feel free to open a feature requests for this.
