### ISSUE TITLE
bug: Incorrect alignment

### ISSUE THREAD

**Issue by zzhaolei** [eza-community/eza#561]
eza version:
```
eza - A modern, maintained replacement for ls
v0.15.0 [+git]
https://github.com/eza-community/eza
```

command-line args:
```
eza --group-directories-first --time-style=relative --icons=auto Library/
```

system:
```macOS 14.0```

<img width="1567" alt="image" src="https://github.com/eza-community/eza/assets/17561793/2d9f8047-c602-4e43-a64b-9f559884b7f5">

**Comment by holmesrichards** [comment]
Duplicate of https://github.com/eza-community/eza/issues/550 ?

**Comment by zzhaolei** [comment]
Sorry, it is indeed a duplicate
