### ISSUE TITLE
feat: support different custom time style for recent/non-recent files

### ISSUE THREAD

**Issue by toymil** [eza-community/eza#563]
## Why

`ls` support this by using a _newline_ in the format string:  
> If FORMAT is `FORMAT1<newline>FORMAT2`, then `FORMAT1` applies to non-recent files and `FORMAT2` to recent files.

With this setup:  
```shell
ls_time_style_short="+\
%Y-%m-%d %H %:::z
--%m-%d %H:%M %:::z\
"
ls_time_style_long="+\
%Y-%m-%d %H:%M:%S %:z
   --%m-%d %H:%M:%S %:z\
"
alias "ll"="ls -AFhl --time-style='${ls_time_style_short}'"
alias "lll"="ls -aFhl --time-style='${ls_time_style_long}'"
```

we have:  
```
$ ll
--08-04 01:51 -05 .gitconfig
--07-30 16:22 -05 .inputrc
2020-01-27 15 -05 .lesshst
2018-04-26 13 -05 .profile

$ lll
   --08-04 05:28:29 -05:00 ./
2018-04-26 13:57:02 -05:00 ../
   --08-04 01:51:31 -05:00 .gitconfig
   --07-30 16:22:42 -05:00 .inputrc
2020-01-27 15:29:17 -05:00 .lesshst
2018-04-26 13:57:02 -05:00 .profile
```

## CLI Proposal

Since we are already incompatible with `ls` due to using `chrono` format string, we don't have to use the same _newline_ approach as in `ls`.

Add an optional `--time-style-custom-recent='+<FORMAT2>'` cli option, if:  
- have `--time-style='+<FORMAT1>'`,  
  have `--time-style-custom-recent='+<FORMAT2>'`;  
  use _FORMAT{1,2}_ for <em>non_recent</em> and _recent_ respectively.
- have `--time-style='+<FORMAT1>'`,  
  do not have `--time-style-custom-recent`;  
  use _FORMAT1_ for both <em>non_recent</em> and _recent_
- have `--time-style` but is not set to custom;  
  ignore `--time-style-custom-recent`

Or we can use the _newline_ approach with the benefit that specifying custom recent format is only possible when using custom time style.

**Comment by cafkafk** [comment]
This seems like a potentially cool, but fairly complicated feature, so I'll look into reviewing this after release today (will not necessarily review today thou)

**Comment by toymil** [comment]
I went with the newline approach, because the extra cli option is not very orthogonal, and all that logic indeed feels unnecessarily complicated.
