### ISSUE TITLE
feat:  pipe paths into eza

### ISSUE THREAD

**Issue by chrisgrieser** [eza-community/eza#608]
Just an idea: How about having the capability to pipe files into eza, to be able to apply eza's colors, icons and so on? 

For example, this would enable you to combine `fd`'s more advanced search options with eza's ability to add icons to files

```bash
fd --min-depth 3 | eza --icons
```

It is certainly a bit farther away from the current usage scenario of eza, but it would fit well into the unix philosophy of having specialized tools working with each other.

**Comment by cafkafk** [comment]
I think it's an interesting idea, I'd lean towards accepting PRs for this, but it would heavily depend on how extensive their changes to the rest of the codebase would be.

**Comment by MartinFillon** [comment]
This is an easy change.

**Comment by chrisgrieser** [comment]
huh, wasn't aware you could simply pass a file as argument to eza as well. That way xargs becomes the solution indeed. Thanks!

**Comment by nabellows** [comment]
Is there any way to make this work with -T tree similar to `tree --fromfile`? As good as the git integration is, fd is much more powerful and I can power more important view via fd but render via eza. Including `.ignore` files that are not specific to git or in git repos
