### ISSUE TITLE
feat:  add icons for coq and ocaml tooling

### ISSUE THREAD

**Issue by 9glenda** [eza-community/eza#611]
- ~~[coq](https://coq.inria.fr/) (`.v`) is a proof assistant and could be represented by `\udb85\udf1b` the nf-md-turkey~~
- dune-project and dune files could be detected as build files

**Comment by PThorpe92** [comment]
I was actually just thinking the same thing not five mins before u posted this I was looking at:

![image](https://github.com/eza-community/eza/assets/121899304/58744a4b-b9a6-4240-91f6-badc17970917)

**Comment by PThorpe92** [comment]
The only issue is `.v` files are currently using V-lang's icon.

**Comment by cafkafk** [comment]
We could always make a flag that makes a call to `file`, although that would probably be horribly slow :(

**Comment by cafkafk** [comment]
Done in  #612
