### ISSUE TITLE
bug: when trying to install eza via pkg, I get connection timed out - http://deb.gierens.de

### ISSUE THREAD

**Issue by Dan1jel** [eza-community/eza#615]
Added as instructed bud can't install due to connection timed out. Anyone know why?

**Comment by PThorpe92** [comment]
Thanks for the bug report.

Yeah my buddy @gierens probably didn't update the repo on the last release. Our apt install Github Action failed for this last night so I figured one of these was coming soon enough. Hopefully should be fixed soon :heart:

**Comment by gierens** [comment]
I'll take of it, should be back in a couple of minutes!

**Comment by gierens** [comment]
Alright, should be back, sorry, my bad ... the VM was accidentally shutdown :innocent:

**Comment by Dan1jel** [comment]
> Alright, should be back, sorry, my bad ... the VM was accidentally shutdown :innocent: 

Super, thanks for the quick action :) case closed.
