### ISSUE TITLE
bug: --grid incorrect alignement when using --icons

### ISSUE THREAD

**Issue by tippex-ls** [eza-community/eza#617]
Hi !

When I use the `--grid` and `--icons` option with eza, the alignement does not seem to count special characters, such as accents `éà...`, resulting in misalignements. There is no such misalignements without `--icons`. For example :

```shell
eza --grid --icons
 agenda.txt                essay_réflexion.doc        meeting_notes.txt       presentation_été.ppt   résumé.doc                        travel_journal.txt
 bill_facture.pdf          family_photo.jpg            newsletter.txt          project_élève.docx     résumé_professionnel.doc          vacation_photo.jpeg
 brochure_été2023.pdf    important_文件.doc        notes_de_musique.txt    receipt_reçu.pdf        résumé_étudiant.doc              vacation_plan.pdf
 budget.xls                important_文檔.doc        painting_peinture.jpg   recipe_œufs.doc         schedule.txt                        éclair_recipe.pdf
 café_menu.docx           invitation_party.doc        party_invitation.doc    recipe_麵.doc           selfie.jpg
 contact_list.txt          invoice_2023.pdf            photo.jpg               report_projet.docx       shopping_list.txt
 contract_étranger.docx   letter_to_professeur.docx   photo_vacances.jpg      report_étude.pdf        song.mp3
 diary_journal.txt         letter_to_élève.doc       poem_poésie.txt        report_été2023.doc     spreadsheet_feuille_de_calcul.xls
 document.txt              map.png                     presentation.ppt        resume_cv.doc            ticket_entrée.pdf
```

```shell
eza --grid
agenda.txt              essay_réflexion.doc        meeting_notes.txt      presentation_été.ppt  résumé.doc                         travel_journal.txt
bill_facture.pdf        family_photo.jpg           newsletter.txt         project_élève.docx    résumé_professionnel.doc           vacation_photo.jpeg
brochure_été2023.pdf    important_文件.doc         notes_de_musique.txt   receipt_reçu.pdf      résumé_étudiant.doc                vacation_plan.pdf
budget.xls              important_文檔.doc         painting_peinture.jpg  recipe_œufs.doc       schedule.txt                       éclair_recipe.pdf
café_menu.docx          invitation_party.doc       party_invitation.doc   recipe_麵.doc         selfie.jpg
contact_list.txt        invoice_2023.pdf           photo.jpg              report_projet.docx    shopping_list.txt
contract_étranger.docx  letter_to_professeur.docx  photo_vacances.jpg     report_étude.pdf      song.mp3
diary_journal.txt       letter_to_élève.doc        poem_poésie.txt        report_été2023.doc    spreadsheet_feuille_de_calcul.xls
document.txt            map.png                    presentation.ppt       resume_cv.doc         ticket_entrée.pdf
```

- The version of eza being used (`eza --version`) : `v0.15.2 [+git]`
- The command-line arguments you are using : `eza --grid --icons`
- Your operating system and hardware platform : through WSL2 on Windows 11, Ubuntu 22.04.3 LTS.

Thanks for your work, eza is a very neat tool !

**Comment by gierens** [comment]
Wait, does this only happend when using `--grid` and `--icons` together? Or does this also happen with just `--grid`?

**Comment by tippex-ls** [comment]
> Wait, does this only happend when using `--grid` and `--icons` together? Or does this also happen with just `--grid`?
Yes, no misalignement without `--icons`

**Comment by gierens** [comment]
I think the accents are not the problem but the icons. Can you upload a screenshot of both cases?

**Comment by tippex-ls** [comment]
I thought so at first, but same icons yield different alignement.
Here's a screenshot !
![Capture d'écran 2023-11-06 111039](https://github.com/eza-community/eza/assets/70751982/20cd80e7-964e-41b0-93c2-4eb0edb5d162)

**Comment by tippex-ls** [comment]
Does not seem to come from my font : last screenshot was with a non-Mono font "FiraCode Nerd Font", but I have the same misalignement with with "FiraCode Nerd Font Mono".

![Capture d'écran 2023-11-06 111836](https://github.com/eza-community/eza/assets/70751982/cdb4a4d6-9588-4ba9-8645-136d71ebbfc7)

**Comment by tippex-ls** [comment]
Yes, seems to be the same bug. Should I close this one ?

**Comment by PThorpe92** [comment]
This is an ongoing issue that we are working on right now. I have a draft of the fix that still has some bugs to work out, it involves a migration to a new major version of the `uutils_term_grid` dependency, and that just turned out to be a little tricky as it involves a fairly substantial rewrite of some calculations. But when it is finished, we shouldn't be having any more issues because the shaky way that things are calculated presently will no longer be :D
Hopefully this gets solved by the next release :+1: 

Closing, as this is indeed the same as #556

**Comment by tippex-ls** [comment]
Fixed in https://github.com/eza-community/eza/releases/tag/v0.17.1 : thanks !
