### ISSUE TITLE
bug: file globs can be interpreted as flags, e.g. `--help` 

### ISSUE THREAD

**Issue by cafkafk** [eza-community/eza#619]
##### version
```
eza - A modern, maintained replacement for ls
v0.15.1 [+git]
```
##### description

If you enter a directory, and touch a file named the same as an eza flag, e.g. `touch --help`, when running `eza *` in that directory on fish shell `version 3.6.1`, eza will not display the files correctly, but rather show the help output.

This issue also exists in e.g. `ls`, so we're by no means alone in this. But we could lead the way by fixing it.

**Comment by bew** [comment]
I'm not sure it's a good idea to 'fix it', as there would be no way to see the help if such a file exists.
If you want to do something about it maybe show a warning if a 'flag' file exist but still do the flag action.
And `eza -- *` should show the files anyway

**Comment by cafkafk** [comment]
I suppose so actually, playing around with solutions, this seems very much like a non-eza problem tbh. Closing as not planned.
