### ISSUE TITLE
bug: `--color-scale` should default to `all`

### ISSUE THREAD

**Issue by cafkafk** [eza-community/eza#634]
The reason for this being a bug and not a feature request is it introduced a breaking change, which affected `zsh-eza`. Having a default behavior makes sense, as it doesn't hurt usability in any way, and spares the user from unnecessary thinking about how they use eza.

Refs: https://github.com/z-shell/zsh-eza/pull/20#issuecomment-1805383943 #628

**Comment by MartinFillon** [comment]
Gonna take a look
