### ISSUE TITLE
eza-wrapper.sh 

### ISSUE THREAD

**Issue by oxo-real** [eza-community/eza#635]
The lastest update of eza unfortunately broke eza-wrapper.sh (https://gist.github.com/eggbean/74db77c4f6404dd1f975bd6f048b86f8).

I now get the following error messages:
`ls` >> `eza: Option --color-scale has no "-g" setting (choices: all, size, age)`
`ls -a` >> `eza: Option --color-scale has no "-a" setting (choices: all, size, age)`
`downgrading package eza (0.15.3-1 => 0.15.2-1)` makes if work again.

Can please someone guide me when this is an easy fix? Thanks!

**Comment by cafkafk** [comment]
Kinda duplicate of #634, for now, you should downgrade to `0.15.2`

**Comment by oxo-real** [comment]
Thanks for your reply @cafkafk 
removing the --color-scale option from eza-wrapper.sh last line makes it function again. 
See https://gist.github.com/eggbean/74db77c4f6404dd1f975bd6f048b86f8#gistcomment-4757354
