### ISSUE TITLE
bug: Incorrect single quote for symbolic link 

### ISSUE THREAD

**Issue by moonfruit** [eza-community/eza#654]
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`)
	<img width="371" alt="图片" src="https://github.com/eza-community/eza/assets/1070090/17cd4361-b15f-4944-8336-f846d9d610bc">

- The command-line arguments you are using
	`eza -l` or `eza -l --icons`

- Your operating system and hardware platform
  <img width="252" alt="图片" src="https://github.com/eza-community/eza/assets/1070090/8f6eef3d-258d-40bb-84d4-7cffd0c2d3d7">

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---

I think the following eza's use of single quotes is wrong.

* `eza -l`
	<img width="951" alt="图片" src="https://github.com/eza-community/eza/assets/1070090/4f12ef41-7287-421f-99bc-6147855b6e8f">

*	`eza -l --icons`
	<img width="964" alt="图片" src="https://github.com/eza-community/eza/assets/1070090/a7b8e7de-a56e-462f-9ae5-c60818f4173a">

**Comment by MartinFillon** [comment]
As I don't have a mac I can't test this, but can you tell me where the quote should be in your opinion

**Comment by holmesrichards** [comment]
I can confirm this in Linux Mint. `ls -l` gives

```
lrwxrwxrwx 1 rsholmes rsholmes 41 Nov 14 14:28 file -> '/home/rsholmes/test/foo bar/baz/test/file'
```

while 'eza -l` gives

```
lrwxrwxrwx - rsholmes 14 Nov 14:28 'file -> /home/rsholmes/test/foo bar/baz/test'/file
```

Placement of both quotes makes no sense in `eza`. `ls` is reasonable.

**Comment by moonfruit** [comment]
@MartinFillon Yes, I think @holmesrichards is right.

**Comment by MartinFillon** [comment]
Okay it clearly needs to be fixed

**Comment by MartinFillon** [comment]
I am either lucky or something, but I cannot reproduce i, can you, anyone that encounter it, precise the commands used to generate the files, the arguments of eza, and the env vars used in the process whatever they are if they are not colors related.

**Comment by holmesrichards** [comment]
```
cd /home/rsholmes
mkdir quotes
cd quotes/
mkdir x\ y
mkdir x\ y/z
touch x\ y/z/u
ln -s /home/rsholmes/quotes/x\ y/z/u ./v
eza -l
```

**Comment by MartinFillon** [comment]
thanks

**Comment by MartinFillon** [comment]
Just tested and on eza v0.15.3 I cannot reproduce it, on eza compiled from main too

**Comment by moonfruit** [comment]
I use homebrew bottled eza, and no eza/exa related environment variables.

**Comment by holmesrichards** [comment]
Some more tests:

```
lrwxrwxrwx - rsholmes 15 Nov 19:30 'v -> /home/rsholmes/quotes/x y/z'/u
drwxrwxr-x - rsholmes 15 Nov 21:35 'x y'
lrwxrwxrwx - rsholmes 15 Nov 21:35 'xyc -> /home/rsholmes/quotes/x y'/c
lrwxrwxrwx - rsholmes 15 Nov 21:32 xyl -> /home/rsholmes/quotes/'x y'
lrwxrwxrwx - rsholmes 15 Nov 21:34 'xyzab -> /home/rsholmes/quotes/x y/z'/'a b'
lrwxrwxrwx - rsholmes 15 Nov 21:37 'xyzijk -> /home/rsholmes/quotes/x y/z/i/j'/k
lrwxrwxrwx - rsholmes 15 Nov 21:33 'xyzl -> /home/rsholmes/quotes/x y'/z
lrwxrwxrwx - rsholmes 15 Nov 21:39 'xyzpqr -> /home/rsholmes/quotes/x y/z/p q'/r
lrwxrwxrwx - rsholmes 15 Nov 21:41 'xyzpqst -> /home/rsholmes/quotes/x y/z/p q'/'s t'
```
It seems the crucial thing is that there's a path component containing a space which is not the final path component. If the only space is in the final component then `eza` puts the quotes around that component, which is not unreasonable. But if there's a space further up, it puts quotes before the link name and after the penultimate path component, before the last slash (regardless of which component has the space). If there are spaces in both locations it does both.

`ls` consistently puts quotes around the whole path:

```
total 4
lrwxrwxrwx 1 rsholmes rsholmes   29 Nov 15 19:30  v -> '/home/rsholmes/quotes/x y/z/u'
drwxrwxr-x 3 rsholmes rsholmes 4096 Nov 15 21:35 'x y'
lrwxrwxrwx 1 rsholmes rsholmes   27 Nov 15 21:35  xyc -> '/home/rsholmes/quotes/x y/c'
lrwxrwxrwx 1 rsholmes rsholmes   26 Nov 15 21:32  xyl -> '/home/rsholmes/quotes/x y/'
lrwxrwxrwx 1 rsholmes rsholmes   31 Nov 15 21:34  xyzab -> '/home/rsholmes/quotes/x y/z/a b'
lrwxrwxrwx 1 rsholmes rsholmes   33 Nov 15 21:37  xyzijk -> '/home/rsholmes/quotes/x y/z/i/j/k'
lrwxrwxrwx 1 rsholmes rsholmes   27 Nov 15 21:33  xyzl -> '/home/rsholmes/quotes/x y/z'
lrwxrwxrwx 1 rsholmes rsholmes   33 Nov 15 21:39  xyzpqr -> '/home/rsholmes/quotes/x y/z/p q/r'
lrwxrwxrwx 1 rsholmes rsholmes   35 Nov 15 21:41  xyzpqst -> '/home/rsholmes/quotes/x y/z/p q/s t'
```

**Comment by MartinFillon** [comment]
Can no longer reproduce on the last eza build and builded from git. Can you confirm fixed ?
![20231202_19h40m02s_grim](https://github.com/eza-community/eza/assets/114775771/3f9245ae-d36e-4f24-9a3c-344c48b7c26d)

**Comment by moonfruit** [comment]
It doesn't look like that's been fixed either from the pictures you posted. And on my computer, eza 0.16.2 not fixes this
