### ISSUE TITLE
feat:  `--time-style=default` but with 12-hour clock and AM/PM indicators

### ISSUE THREAD

**Issue by obscenelyvague** [eza-community/eza#672]
The default time style format is nice and I'm a fan of how the year is printed only if the file _isn't_ from the current year. I believe it isn't possible to recreate the default format with prefixes. Currently, the default format code does this:

```    let month = &*LOCALE.short_month_name(time.month0() as usize);
    let month_width = short_month_padding(*MAX_MONTH_WIDTH, month);
    let format = if time.year() == *CURRENT_YEAR {
        format!("%_d {month:<month_width$} %H:%M")
    } else {
        format!("%_d {month:<month_width$}  %Y")
    };
```

What I want is to replace `%_d {month:<month_width$} %H:%M` with `%_d {month:<month_width$} %I:%M %p`

A separate global option to treat all time in the 12-hour convention perhaps? Any other ideas to implement this as an option in a non-convoluted way?

**Comment by holmesrichards** [comment]
Maybe I'm misunderstanding your request, but what's wrong with `--time-style '+%_d %b %I:%M %p'`?

**Comment by obscenelyvague** [comment]
>but what's wrong with `--time-style '+%_d %b %I:%M %p'`?

I like that the `custom` format only prints year for a file if the file hasn't been modified in the current year. e.g., [1] **18 Nov 22:40** for a file modified this year and [2] **18 Nov  2022** for a file modified last year. I want [1] to follow 12-hour clock convention is all.

**Comment by holmesrichards** [comment]
https://github.com/eza-community/eza/pull/564 would address that, I think, allowing you to specify for instance '+%_d %b %I:%M %p' for recent files and '+%_d %b %Y' for non recent.

**Comment by obscenelyvague** [comment]
Closing since 422efee has been merged.
