### ISSUE TITLE
bug: completion does not work depending on the `--icons` agument

### ISSUE THREAD

**Issue by LorenzoBettini** [eza-community/eza#692]
I'm using

```
eza --version
eza - A modern, maintained replacement for ls
v0.16.1 [+git]
```

Both on Arch and Ubuntu.
I was using exa and then I switched to eza.

I had aliases of the shape (that I updated for eza)

```
alias l='eza -lah --color=always --group-directories-first --icons' # with headers
```

and if I type `l` and then TAB for completion it does not show directories as completions.
If I switch `--icons` not to be the last argument, then everything works again:

```
alias l='eza -lah --color=always --icons --group-directories-first' # with headers
```

**Comment by PThorpe92** [comment]
Yeah it makes sense...  
 `--icons` is actually supposed to take an argument (`always`, `auto`, `never`) but `auto` is defaulted so I can see why tab completion wouldn't work, as it is expecting an argument. 

Not sure exactly how to fix this, other than to alter the completions incorrectly :thinking:

**Comment by LorenzoBettini** [comment]
@PThorpe92 OK, thanks for the clarification!
That's something different from exa, then, isn't it?
I'm fine with updating the alias, which makes even more sense now that you told me that.
I took that alias from somewhere, but I don't remember.
Please, feel free to close this.

**Comment by PThorpe92** [comment]
Yeah it just came from modifications and features we have added. Thanks for pointing it out though, next time I'm in that part of the code base i'll see about how it might be fixed but I know since it's looking for an argument it might be a pain. 

:heart:
