### ISSUE TITLE
Unable to locate package eza

### ISSUE THREAD

**Issue by Hurpster** [eza-community/eza#696]
Setting up my new setup, following the install.md steps for ubuntu ( im on ubuntu 22.04):
sudo mkdir -p /etc/apt/keyrings
wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
sudo apt update
sudo apt install -y eza
running this gives me: 
"unable to locate package eza"
Rest of the commands/steps work fine
Anyone has any ideas? Appreciate in advance

**Comment by axeld-galadrim** [comment]
Are you sure that the rest of the commands work ? 
I personally get:
`E: The repository 'http://deb.gierens.de stable InRelease' is not signed.`
And after that, I get `E: Unable to locate package eza` which therefore makes sens.

**Comment by MartinFillon** [comment]
Cannot reproduce too, on ubuntu machine and on docker
