### ISSUE TITLE
feat:  display  file/folder names with full path

### ISSUE THREAD

**Issue by j-xella** [eza-community/eza#726]
It would be nice to have a flag to toggle the display of full paths with file and folder names.

Something similar to `find $PWD | xargs ls -ld`

You don't need this often, but sometimes such behaviour is desired if you plan to copy/paste file names to another terminal window, for example.

**Comment by MartinFillon** [comment]
This is a great idea

**Comment by taminob** [comment]
I'd like to work on this and will work on a proposal for the feature.

**Comment by j-xella** [comment]
The new `--absolute` option does not seem to be mentioned in `eza.1.md` ...
