### ISSUE TITLE
bug: Your flake inputs cause breakage

### ISSUE THREAD

**Issue by LucianU** [eza-community/eza#732]
I was using `eza` as a flake input in my system flake. At some point, I started seeing this error:

```
error: NAR hash mismatch in input 'http://rime.cx/v1/github/semnix/flake-utils.tar.gz?narHash=sha256-zsNZZGTGnMOf9YpHKJqMSsa0dXbfmxeoJ7xHlrt+xmY=' (/nix/store/pgid9c9xfcrbqx2giry0an0bi0df7s5c-source), expected 'sha256-zsNZZGTGnMOf9YpHKJqMSsa0dXbfmxeoJ7xHlrt+xmY=', got 'sha256-kAuep2h5ajznlPMD9rnQyffWG8EM/C73lejGofXvdM8='
```

I think it has something to do with the fact that there is no version in that `flake-utils.tar.gz` file, so when it's updated, the NAR hash mismatch occurs.

This issue prevents the system from being updated, so I had to remove `eza` unfortunately.

**Comment by cafkafk** [comment]
Will investigate, hopefully before Christmas if time permits.

**Comment by LucianU** [comment]
Thanks. There's no rush. In the meantime, I discovered that eza is provided by newer versions of nixpkgs, so I can use it from there if I want.

**Comment by cafkafk** [comment]
This should have been solved now on the latest version on the main branch by commit 3c31fe09d217c4405fcd9c9d1155c52d722e36e0, if the issue persists for you, please feel free to reopen.
