### ISSUE TITLE
feat:  Automatic Color Adjustment for ".bak" Files in "eza"

### ISSUE THREAD

**Issue by adoolaard** [eza-community/eza#733]
Feature Request:
I would like to propose the addition of automatic color adjustment for files with the ".bak" extension in the "eza" tool, similar to the behavior in the "exa" tool. Currently, when using "exa," files with the ".bak" extension are automatically displayed with a gray color, facilitating quick identification of backup files in the file listing.

Reasoning:
This feature proves to be quite helpful in distinguishing backup files from regular ones, providing a visual cue that aids in efficient file management. As "eza" is an advanced and actively maintained tool, incorporating this feature would enhance its usability and maintain consistency with user expectations.

Implementation Details:
If this feature aligns with the design philosophy of "eza," I request guidance on how to enable it or, if not, consideration for its inclusion in future releases.

Additional Information:

"eza" version: v0.17.0
Operating System: macOS Sonoma

Thank you for considering this feature request, and I appreciate your efforts in continually improving the "eza" tool.

**Comment by adoolaard** [comment]
And maybe there could also be an option to show the git ignored files in a different color, such as grey.

**Comment by MartinFillon** [comment]
So you are telling me that it worked well in `exa` ?

**Comment by cfxegbert** [comment]
`.bak` are already categorized as `FileType::Temp`.  You can use the `tm` color to change the color of all temporary files.

**Comment by pesterhazy** [comment]
Grey for temp files (e.g. `.crdownload` extension) is hard to read so I used this to turn off this feature

```
EZA_COLORS="tm=0"
```

**Comment by adoolaard** [comment]
Thanks everyone for your comments! I didn't realize you could already customize the color for `.bak` files using the `tm` option (thanks @cfxegbert and @pesterhazy ). I've gone ahead and marked this issue as resolved.
