### ISSUE TITLE
bug: grid layout column wise not correctly rendering.

### ISSUE THREAD

**Issue by darshanCommits** [eza-community/eza#739]
- The version of eza being used 0.15.0-1 (aur)
- The command-line arguments you are using eza -aF --icons --group-directories-first
- Your operating system and hardware platform arch linux, wezterm/foot terminals
---
![image](https://github.com/eza-community/eza/assets/104432537/5b4f1303-363d-4cca-902b-99ad426c8e2e)
![image](https://github.com/eza-community/eza/assets/104432537/af2e0f22-faa9-4900-a448-b328f6537372)

~~The grid layout should be column staggered and not row staggered like it is now.~~
~~This results in random line breaks and overall unaesthetic output.~~
~~Another fix could be to dynamically set the number of columns based on the largest file/dir name.~~

Apparently after more testing I found out it happens regardless, see the 2ns screenshot, 1st row, there's plenty space yet.

 
ps It'd be nice to specify the number of columns instead of just 1 as in -1 flag but thats out of scope of this issue.

**Comment by rsholmes** [comment]
What output are you expecting when there are long names?

**Comment by darshanCommits** [comment]
> If you are referring to the misalignment of the first line of output, that's due to eza not correctly figuring the width for file names that contain spaces around which it puts quotes. 

Yes, exactly this. Misalignment, that would be the more appropriate word to describe this.

> I believe that's a bug still being worked on. 
duplicate issue? can you link the original.

**Comment by PThorpe92** [comment]
Yes, this has been an ongoing issue I've been working on. Unfortunately the solution is not so simple and involves a pretty serious migration from at least two major dependencies (or a new major version.) Every time I make progress, I run into something unrelated that breaks or a feature that will need to be completely reimplemented. I just haven't had the time to finish it.

Luckily holiday break gives me time to work on eza, really hoping to tackle this in the next week or so :+1:

**Comment by darshanCommits** [comment]
> Luckily holiday break gives me time to work on eza, really hoping to tackle this in the next week or so :+1: 

Looking forward to your pr.
Thanks for your work.
