### ISSUE TITLE
bug: The `--icons` option breaks the grid layout when using with non-ASCII symbols

### ISSUE THREAD

**Issue by Ledity** [eza-community/eza#752]
Distro: Arch Linux x86.

```
$ eza --version 
eza - A modern, maintained replacement for ls
v0.17.0 [+git]
https://github.com/eza-community/eza
```

As you can see on the picture, the `eza`'s default output (or with --grid flag) correctly estimates the length of a Unicode filename.
However, with the `--icons` flag, it suddenly stops counting the Unicode string length and instead uses the number of bytes in the string as the column length.
![Снимок-01 01-00004](https://github.com/eza-community/eza/assets/70322358/55bbe72a-a372-4ec3-a99d-72f0b525dec9)
It can be clearly seen in lines 1 and 2 of the `eza --grid --icons` output, where the word "Загрузки"  is 4 letters longer than the word "Игры" and in the next column the word "Общедоступные" is shifted 4 symbols to the left comparing to the next line.
(Note that 'З' is cyrillic for 'Z', not the digit 3).

**Comment by Ledity** [comment]
The `eza-git` AUR package solves the issue. Waiting for the package to update in the repo.

**Comment by PThorpe92** [comment]
Thankfully this issue has been fixed and merged into main. :+1: 

Will be avail on next release :D

**Comment by cafkafk** [comment]
> Will be avail on next release :D

Which will be tomorrow!
