### ISSUE TITLE
bug: Alignment issue.

### ISSUE THREAD

**Issue by sandenbergmelo** [eza-community/eza#757]
`eza --version` : `v0.17.0 [+git]`.

Running `eza --icons=auto --no-quotes --group-directories-first`.

OS: Ubuntu 22.04.3 LTS.

#### I'm having this alignment problem on my PC:
![image](https://github.com/eza-community/eza/assets/77549672/78db2574-4390-45ee-8901-b735835ec940)

**Comment by PThorpe92** [comment]
Thankfully there is a fix for this merged into `main` :+1:  will be in the next release
#742
