### ISSUE TITLE
bug: eza slow in home directory

### ISSUE THREAD

**Issue by apmyplol** [eza-community/eza#760]
Ive noticed that suddenly my prompt became really slow and after deactivating starship prompt I noticed that only the eza command is slow.
More precisely the command runs slow only in my home directory and runs normally in other directions.
I manage my dotfiles with a bare git repo in my home dir, maybe this has some impact, although this would be weird imo.
`eza --no-git` in my home dir is also very slow (like 20 seconds, `ls` runs normally), and running `eza` *with git* in other git directories works as usual.

I am very grateful if someone could give me a hint how this problem could be solved, thanks.

- version: 0.17.0
- `eza --no-git`
- arch linux

**Comment by daviessm** [comment]
Are you comfortable building `eza` from source and running a debug build? I could add some debug logging to show how long it takes to read each file, to see if any of them stand out as being unusually slow.

**Comment by apmyplol** [comment]
Yeah I could try to do that.
I only have a little bit of experience with building from source, so I probably would need an instruction to follow.

Ive also tried downgrading `eza` but this did also not solve the problem. The weird thing is that I did not have this problem the last time I used my PC like 1 week ago, it just popped up suddenly out of nowhere.

**Comment by apmyplol** [comment]
Ok nvm, Im sorry im hella stupid.
I have symlinks to shared folders in my home directory and someone turned off the server that these folder are connected to..... 🤦🤦🤦
Thank you for your help tho :pray:

**Comment by apmyplol** [comment]
Ok nvm, Im sorry im hella stupid.
I have symlinks to shared folders in my home directory and someone turned off the server that these folder are connected to..... 🤦🤦🤦
Thank you for your help tho :pray:

**Comment by daviessm** [comment]
No worries, I thought it would be something like that!
