### ISSUE TITLE
bug: crash (core dump) when using --git-repos flag on a directory with no read permission

### ISSUE THREAD

**Issue by sheeit** [eza-community/eza#767]
<details>
<summary>Version information</summary>
OS: Arch Linux, kernel verson 6.6.8-arch1-1, x86_64

eza version: v0.17.0 [+git] (the one package by Arch)
</details>

How to reproduce:

```console
$ mkdir -m 100 foo
$ RUST_BACKTRACE=1 eza -l --git-repos foo
thread 'main' panicked at src/main.rs:203:14:
called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)
$ echo $?
134
$ eza --version
eza - A modern, maintained replacement for ls
v0.17.0 [+git]
https://github.com/eza-community/eza
```

This bug only occurs if the read permission is missing for the directory, not the execute or the write permissions, and only for the `--git-repos` and `--git-repos-no-status` flags, the `--git` flag just shows `Permission denied (os error 13)`.

**Comment by cafkafk** [comment]
Can reproduce on x86_64 GNU/Linux, thanks for the clear bug report!
