### ISSUE TITLE
feat:  Git hidden files

### ISSUE THREAD

**Issue by sayMuFaSa** [eza-community/eza#782]
By default when --git option is used show also hidden files (aka started with dot) that are tracked in the repo. This might be useful when for example .gitignore is a part of the repo.

**Comment by hasecilu** [comment]
You mean only targeting git files `.env`, `.mailmap`, `.gitmodules`? What would be the difference with using `-a` flag?

**Comment by sayMuFaSa** [comment]
No need for this feature.
