### ISSUE TITLE
bug:  `rsync`, `scp` comman can't complete path

### ISSUE THREAD

**Issue by kdurant** [eza-community/eza#784]
- eza verion:  v0.17.1
- os: ubuntu22.04

```bash
    sudo mv /usr/bin/ls /usr/bin/ls_old
    sudo ln -s /usr/bin/eza  /usr/bin/ls
```
When I do this, `rsync`, `scp` comman can't complete path.

![Peek 2024-01-17 10-12](https://github.com/eza-community/eza/assets/2704364/60a7c0f7-84c2-4d42-99ce-d7c27fe79c60)

**Comment by MartinFillon** [comment]
Hey, so as of what I see I think setting up an alias in your shell configuration file is better in your case, as it seems that your shell rely on gnu ls to do its autocompletion.

**Comment by PThorpe92** [comment]
`alias ls='eza -lAh'`... (whatever flags you want in the command by default)

not generally a good idea to move ls out of your /usr/bin as many other programs generally can rely on it under the hood
