### ISSUE TITLE
feat:  --classify=auto

### ISSUE THREAD

**Issue by bisho** [eza-community/eza#785]
The visual markers from `--classify` are very handy, so I love to keep them on by default on my `ls` alias, but when piping the output to other commands, you can get bitten by it, as it will contain some extra characters like`*` for executables. Then I need to remember to use `\ls` to skip the alias or creating different aliases for different purposes.

For example:

```
$ ls -f | while read file; do grep 'foo' "$file"; done
grep: some_executable.sh*: No such file or directory
```

It would be amazing to have a `--classify=auto`, that will enable classify only for tty output, similar to `--color=auto` that disables colors for pipes.

**Comment by bew** [comment]
Note that in your example you'd be better of using your shell to list files instead of relying on `ls`, like so:
```sh
for file in *; do echo "file: $file"; done
```

**Comment by bisho** [comment]
> Note that in your example you'd be better of using your shell to list files instead of relying on `ls`, like so:
> 
> ```shell
> for file in *; do echo "file: $file"; done
> ```

Sure, it was just an example, i use `find` and `*` as well in a lot of cases, but sometimes you just used `ls` and want to pipe that content somewhere, to a file for example. You can do that with shell's `*`, but becomes quickly cumbersome. For example you can't do `echo * > file`, as they will be space separated and break if filenames contain spaces. You will need a `for file in *; do echo "$file" >> file; done` instead of a quick `ls > file`... You get the idea...
