### ISSUE TITLE
bug: icons displayed as empty squares (also in the demo on eza.rocks)

### ISSUE THREAD

**Issue by aviad** [eza-community/eza#793]
- eza version
```
» eza --version                                                       
eza - A modern, maintained replacement for ls
v0.17.0 [+git]
https://github.com/eza-community/eza
```

- The command-line arguments you are using
`eza -l --icons`

- Your operating system and hardware platform
```
» lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	23.1.3
Codename:	Vulcan

» echo $TERM
rxvt-unicode-256colo

» i3 --version
i3 version 4.23 (2023-10-29) © 2009 Michael Stapelberg and contributors

```
---

![demo](https://github.com/eza-community/eza/assets/488985/27b89af9-405c-4918-92e9-b0a262d43ae2)

**Comment by MartinFillon** [comment]
this is a font issue,  your font doesnt seem to know which chars those are

**Comment by aviad** [comment]
I tried many of the nerd fonts, none of which is able to print these chars. 
Is there a recommended font I can try to make sure it's indeed a font issue? 
Seeing this on the eza official demo animation on https://eza.rocks made me wonder if this is not a regression.

**Comment by aviad** [comment]
this is an issue with URxvt, not eza

**Comment by MartinFillon** [comment]
> this is an issue with URxvt, not eza

Thanks for the heads up and fyi i use JetBrains Mono Nerd Font
