### ISSUE TITLE
feat:  Dates are colored according to file age

### ISSUE THREAD

**Issue by jensenr30** [eza-community/eza#798]
It would be cool if there was an option to color the dates by when the file was last modified.  More recent files could have their dates colored with a bright color, and older files could have their dates colored with a darker color.

E.g.
```
if (age < 5 minutes):
    color = red
if (age < 60 minutes
    color = yellow
if (age < 1 day)
    color = green
if (age < 1 month) 
    color = light blue
if (age < 1 year
    color = blue
else
    color = purple
```
I attached a rough concept of how this feature would look.
![rainbowdates](https://github.com/eza-community/eza/assets/3083835/4661f701-4323-4e66-a230-866e46a431ca)

**Comment by Delapouite** [comment]
Hi. eza 0.15.3 introduced `--color-scale`, is it similar to your suggestion? 

https://github.com/eza-community/eza/releases/tag/v0.15.3

**Comment by jensenr30** [comment]
@Delapouite 
Thank you!
I should have RTFM...
