### ISSUE TITLE
feat: Windows: Extra cli flags for distinguishing dotfiles and hidden files

### ISSUE THREAD

**Issue by lesleyrs** [eza-community/eza#805]
On Windows it should show dotfiles by default which is how `ls` works on here, but NOT the hidden files like NTUSER. It creates too much output for even a small directory.

**Comment by DWTW321** [comment]
Could figure out how to make it work with eza but with lsd on windows you can do this to hide those files but still show other hidden files.
`lsd.exe -A --group-directories-first --hyperlink "always" -I "ntuser.**" -I "NTUSER.**"`

**Comment by cafkafk** [comment]
Maybe https://github.com/eza-community/eza/issues/336 might be related, what version of eza are you on @lesleyrs ?

**Comment by lesleyrs** [comment]
0.18.5 It still happens when running `eza -la` in home directory/user folder.

**Comment by cafkafk** [comment]
I don't have a windows computer to test/work on this unfortunately

**Comment by lesleyrs** [comment]
To be more specific I'd like to have this changed:
```rust
-                // Windows has its own concept of hidden files, when dotfiles are
-                // hidden Windows hidden files should also be filtered out
+                // Windows has its own concept of hidden files, which should also be filtered out
                 #[cfg(windows)]
-                if !self.dotfiles && file.as_ref().is_ok_and(|f| f.attributes().hidden) {
+                if file.as_ref().is_ok_and(|f| f.attributes().hidden) {
```

But there should probably be some way to enable them again with double `-a` or something. You often want to see dotfiles on windows but not hidden files.

**Comment by kernkraft235** [comment]
I commented about a similar issue with macOS which also handles hidden files differently.
If this dual-layer hidden feature gets implemented, I'd find it useful in Linux, MacOS, and Windows. I have to use all 3 and for visual reasons I really like minimizing the "noise", but sometimes you just cant remove a folder/file

You could use -V (verbose all) or piggyback off of the -A/-a difference
Or for maximum compatibility make the feature "opt-in". I think most people are aliasing anyways

https://github.com/eza-community/eza/issues/309#issuecomment-1993365840
