### ISSUE TITLE
bug: eza does not follow LSCOLORS

### ISSUE THREAD

**Issue by pravic** [eza-community/eza#814]
- The version of eza being used (`eza --version`): v0.18.0 [+git]
- The command-line arguments you are using: `LSCOLORS='cx' eza --color=always`
- Your operating system and hardware platform: macOS 13.4
- Terminal: macOS "Terminal" with "Pro" theme

---

<img width="821" alt="image" src="https://github.com/eza-community/eza/assets/724639/798dc80a-72bd-4c06-80aa-ca63aa93e046">

**Comment by Mylloon** [comment]
The variable used is `EXA_COLORS`

**Comment by MartinFillon** [comment]
please see https://github.com/eza-community/eza/blob/main/man/eza_colors.5.md

**Comment by pravic** [comment]
Yes, but `eza` advertises itself as

> A modern, maintained replacement for ls

Though it does not use the word "compatible". All right, not a bug then o/

**Comment by cafkafk** [comment]
> Yes, but `eza` advertises itself as
> 
> > A modern, maintained replacement for ls
> 
> Though it does not use the word "compatible". All right, not a bug then o/

There's a catchall discussion for issue with eza colors here: https://github.com/orgs/eza-community/discussions/359

As you say, this isn't a bug, so closing for now.
