### ISSUE TITLE
refactor: Move to uutils-term-grid

### ISSUE THREAD

**Issue by cafkafk** [eza-community/eza#83]
I'm pretty sure we should move to https://github.com/uutils/uutils-term-grid (see https://github.com/ogham/rust-term-grid/pull/15).

See: https://github.com/cafkafk/eza/issues/66 for more context.

**Comment by cafkafk** [comment]
This isn't on crates.io, I'll contact upstream to get them to publish it... I'd really love if we'd not have to fork it as well :s

**Comment by MartinFillon** [comment]
done in #536
