### ISSUE TITLE
bug: error render hyperlinks when files contain space and utf8 char

### ISSUE THREAD

**Issue by XhstormR** [eza-community/eza#843]
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`): v0.18.2
- The command-line arguments you are using: `eza -l --hyperlink`
- Your operating system and hardware platform: MacOS Darwin 23.3.0 x86_64 i386

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

---

I use the hyperlinks function to open a folder, but it doesn't work when the file contains both spaces and Chinese characters. 

`ab cd` works well，`健身 资料` doesn't.

```shell
$ command eza -l --hyperlink  
drwxr-xr-x - user 15 Feb 15:45 'ab cd'
drwxr-xr-x - user 15 Feb 15:45 '健身 资料'
```

![image](https://github.com/eza-community/eza/assets/10527522/a5fe976f-a297-46ce-afb7-cd024dfeae3b)

**Comment by XhstormR** [comment]
the space need to be convert to `%20`

**Comment by wangyandongnx** [comment]
+1
