### ISSUE TITLE
bug: Incorrent alignment when using -F=auto

### ISSUE THREAD

**Issue by ad-chaos** [eza-community/eza#845]
- v0.18.3 [+git]
- `eza --icons -F`
- MacOS M1
---

**Screenshot**
<img width="1403" alt="Screenshot 2024-02-16 at 10 40 59 PM" src="https://github.com/eza-community/eza/assets/90276965/cc35edd5-51d2-40f9-b6b5-97eb9442450f">

I bisected the code and found this commit to be the culprit: https://github.com/eza-community/eza/commit/367ff558a683e05d2c4b2c8bf583f06de1f39958

**Comment by PThorpe92** [comment]
interesting. i knew there was an issue leftover from classify w/ utf8 chars, but I didn't know it would only trigger on `auto`. 

Thanks for reporting this :+1:

**Comment by ad-chaos** [comment]
Would love if you could make a release for this (since it was sorta breaking)

Thanks for the fix!

**Comment by cafkafk** [comment]
> Would love if you could make a release for this (since it was sorta breaking)

Our normal release schedule is every thursday, hopefully that's reasonably soon enough?

**Comment by ad-chaos** [comment]
Yup, that definitely works
