### ISSUE TITLE
feat:  Can you support installing via conda-forge?

### ISSUE THREAD

**Issue by nyngwang** [eza-community/eza#846]
As title. `conda search eza` found nothing.

**Comment by apoorvkh** [comment]
+1 that would be really great, thank you!

**Comment by cafkafk** [comment]
I'm sure there's also some place to ask for this upstream, I'm sure it will get more attention there :)

**Comment by KGrewal1** [comment]
Just came across this and would be helpful too (by upstream where do you mean, as happy to help if needed?)

**Comment by cafkafk** [comment]
eza is on conda-forge https://anaconda.org/conda-forge/eza

**Comment by KGrewal1** [comment]
Sorry to post on the closed, but would it be possible to distribute aarch64 linux on conda too (didn't think this was different enough to merit another issue)

**Comment by cafkafk** [comment]
I think that's again something to bring upstream instead of here, https://github.com/conda-forge
