### ISSUE TITLE
Build v0.18.4 on NetBSD10RC4

### ISSUE THREAD

**Issue by naguam** [eza-community/eza#861]
Hello,

I tried to install eza on NetBSD10 RC4 outside from the version in pkgsrc through `cargo install eza` and with libgit and libcurl and else linked with; in .cargo/config :
```
[target.x86_64-unknown-netbsd]
rustflags = ["-C", "link-args=-Wl,-R/usr/pkg/lib"]
```
(no libtool by default on NetBSD but pkgsrc version might install and use it)

- It is eza version v0.18.4 
- Rust netbsd version:  rustc 1.73.0 (cc66ad468 2023-10-03)

- and config:
```
$ rustc --print cfg
debug_assertions
panic="unwind"
target_arch="x86_64"
target_endian="little"
target_env=""
target_family="unix"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="netbsd"
target_pointer_width="64"
target_vendor="unknown"
unix
```

Here is the error:
```
error: linking with `cc` failed: exit status: 1                                                                       
  |                                                                                                                   
  = note: LC_ALL="C" PATH="/usr/pkg/lib/rustlib/x86_64-unknown-netbsd/bin:/home/naguam/.cargo/bin:/usr/pkg/java/openjd
k17/bin:/usr/pkg/sbin:/usr/pkg/bin:/home/naguam/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R7/bin:/usr/pkg/bin:/usr/pkg
/sbin:/usr/games:/usr/local/bin:/usr/local/sbin" VSLANG="1033" "cc" "-Wl,-L/usr/pkg/lib/libatomic" "-m64" "/tmp/rustc3
VUv44/symbols.o" "/tmp/cargo-installQfP0Zm/release/deps/eza-36627e75085c137a.eza.3d1ab9f77878754a-cgu.0.rcgu.o" "-Wl,-
-as-needed" "-L" "/tmp/cargo-installQfP0Zm/release/deps" "-L" "/tmp/cargo-installQfP0Zm/release/build/libgit2-sys-a091
6002135398e2/out/build" "-L" "/usr/pkg/lib/rustlib/x86_64-unknown-netbsd/lib" "-Wl,-Bstatic" "/tmp/rustc3VUv44/liblibg
it2_sys-38d9318d26a2d2e7.rlib" "/usr/pkg/lib/rustlib/x86_64-unknown-netbsd/lib/libcompiler_builtins-dcf87f8b2c75a1a2.r
lib" "-Wl,-Bdynamic" "-lz" "-lutil" "-lrt" "-lutil" "-lexecinfo" "-lexecinfo" "-lpthread" "-lrt" "-lgcc_s" "-lc" "-lm"
 "-lrt" "-lpthread" "-lutil" "-lrt" "-lutil" "-lexecinfo" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/usr/pkg/lib
/rustlib/x86_64-unknown-netbsd/lib" "-o" "/tmp/cargo-installQfP0Zm/release/deps/eza-36627e75085c137a" "-Wl,--gc-sectio
ns" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-Wl,--strip-all" "-Wl,-R/usr/pkg/lib"                                     
  = note: ld: /tmp/cargo-installQfP0Zm/release/deps/eza-36627e75085c137a.eza.3d1ab9f77878754a-cgu.0.rcgu.o: in functio
n `eza::output::table::Table::display':
          eza.3d1ab9f77878754a-cgu.0:(.text._ZN3eza6output5table5Table7display17h23df455df1d82620E+0x4b7): undefined r
eference to `fflagstostr'
                                                           
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path
 specified                                                 
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc
.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
                             
error: could not compile `eza` (bin "eza") due to previous error
error: failed to compile `eza v0.18.4`, intermediate artifacts can be found at `/tmp/cargo-installQfP0Zm`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

At first I though I just made a mistake in my linking configurtion to access pkgsrc installed libraries, but with other programs such as bat, this is my linking configuration that actually fixed the missing linking and made my binaries work (proper linking rpath)

Furthermore, `fflagstostr` seems to be a FreeBSD specific library function despite being mentioned in NetBSD man pages for other functions (maybe from code imports, or comparison, as `fflagstostr` has no dedicated manual pages in NetBSD contrary to FreeBSD.

Now somebody seems to have managed having it right in pkgsrc.
Maybe I made a mistake. In any case, I'm happy if this could help bringing a fix.

It seems they added a fix on pkgsrc https://pkgsrc.se/files.php?messageId=20231230030848.AE0E8FA42@cvs.NetBSD.org but it could be nice for it to build natively from upstream.

Cheers,

---

**Comment by daviessm** [comment]
Hi @naguam, I don't think any of the developers use NetBSD but if you can get it to build and submit a patch we'd be happy to review and include it. Do the changes in http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/sysutils/eza/patches/patch-src_output_render_mod.rs?rev=1.1&content-type=text/x-cvsweb-markup allow it to build if you apply them manually along with the MAKE_ENV and RUSTFLAGS from http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/sysutils/eza/Makefile?rev=1.20&content-type=text/x-cvsweb-markup?

**Comment by naguam** [comment]
Hi,

I implemented a fix regarding the maintainer comment.


I am not yet proficient in Rust and for example I used the `#[cfg]` as I saw elsewhere in the code.

But I did my best and it seems to work.

As flags are common in most BSD and only NetBSD having a different function, I decided there was not need for a new file for this and just added the modifications in the sale flags_bsd.rs.




Regarding your second link about MAKE_ENV and RUSTFLAGS.

Honestly these are related to openssl in the pkgsrc version and I don't know much about it.

I haven't had any problems building eza with `cargo install` or `cargo build`  related to this.

I prefer to let the pkgsrc maintainer to decide if it is still necessary as I am not sure if this is still relevant.

NetBSD 10 does have openssl 3.X anyway and the patch seems related to openssl 1.1.1.u.

I think I will try to send him an email regarding the file flags fix anyway, so I will be able to ask about this as well.

**Comment by daviessm** [comment]
> @naguam If, `eza` updates the crate dependency on `openssl-src` to the [300 series](https://github.com/alexcrichton/openssl-src-rs/tags), we can remove the crate patch. The target defaults are already defined there, _e.g._ [aarch64-unknown-netbsd](https://github.com/alexcrichton/openssl-src-rs/blob/30860617df584f1ec6f3a3f55d3cf638aab5ea0b/src/lib.rs#L277) but, they are not defined in the 111 series still in [use by eza](https://github.com/eza-community/eza/blob/687a8bf633f7a0fcff7feba9d0e22f7405a2fb0e/Cargo.lock#L708)

Yeah, looks like that dependency comes via `git2` so it'll get updated whenever that bumps its deps and we bump the package.

**Comment by 0323pin** [comment]
@daviessm 
```
~> cd eza-0.18.5
~> cargo tree
...
 9 ├── git2 v0.18.2
 10 │   ├── bitflags v2.4.0
 11 │   ├── libc v0.2.153
 12 │   ├── libgit2-sys v0.16.2+1.7.2
 13 │   │   ├── libc v0.2.153
 14 │   │   └── libz-sys v1.1.2
 15 │   │       └── libc v0.2.153
 16 │   │       [build-dependencies]
 17 │   │       ├── cc v1.0.79
 18 │   │       │   └── jobserver v0.1.22
 19 │   │       │       └── libc v0.2.153
 20 │   │       └── pkg-config v0.3.19
 21 │   │   [build-dependencies]
 22 │   │   ├── cc v1.0.79 (*)
 23 │   │   └── pkg-config v0.3.19
 24 │   ├── log v0.4.20
 25 │   └── url v2.2.1
 26 │       ├── form_urlencoded v1.0.1
 27 │       │   ├── matches v0.1.8
 28 │       │   └── percent-encoding v2.3.1
 29 │       ├── idna v0.2.3
 30 │       │   ├── matches v0.1.8
 31 │       │   ├── unicode-bidi v0.3.5
 32 │       │   │   └── matches v0.1.8
 33 │       │   └── unicode-normalization v0.1.17
 34 │       │       └── tinyvec v1.2.0
 35 │       │           └── tinyvec_macros v0.1.0
 36 │       ├── matches v0.1.8
 37 │       └── percent-encoding v2.3.1
...
```

**Comment by 0323pin** [comment]
Ahh ... it's an [optional dependency](https://github.com/rust-lang/git2-rs/blob/3da58f3ee344278115f87b7b2d82a5ecc294a170/Cargo.toml#L26) so, `cargo tree` doesn't pick it

![2024-03-01-093940_1103x495_scrot](https://github.com/eza-community/eza/assets/90570748/0bf783d5-c330-4c81-bce1-e92daa47aa2a)
