### ISSUE TITLE
feat:  add --group-files-first or --group-directories-last 

### ISSUE THREAD

**Issue by 20manas** [eza-community/eza#872]
Currently, there is an option to show all the directories before all the files using `--group-directories-first`. However, it is often useful to do the reverse, i.e., show all the files before all the directories.

For example, it will be quite useful to use this feature alongside `--tree` as then when printing a deeply nested directory structure, all the files within each directory will be listed first and then the remaining deeply nested directory subtree within it will be printed, giving the users a far better understanding of which files are within each folder.

**Comment by cafkafk** [comment]
This does actually sound super useful, hope someone pick this up, we'd gladly accept a pr for this.

**Comment by erwinvaneijk** [comment]
Useful, I'm working on it.

**Comment by erwinvaneijk** [comment]
This is now addressed in #1172.
