### ISSUE TITLE
bug: Nerd Fonts icons not rendering correctly

### ISSUE THREAD

**Issue by TallonRain** [eza-community/eza#885]
Hi there, I'm using the current version of Nerd Fonts (3.1.1) with the Jetbrains Mono font and I've just recently switched to eza. However, I've found that when using the `--icons` flag, the relevant icons are not rendering correctly. But they still render correctly with exa. Here's a comparison:

<img width="529" alt="image" src="https://github.com/eza-community/eza/assets/4109831/a0eae2cb-8ec5-49d5-addd-9c5c57972e2d">

This is on macOS on iTerm2.

<img width="374" alt="image" src="https://github.com/eza-community/eza/assets/4109831/aa004931-c9c3-4d2f-a871-420340fdf654">

**Comment by cafkafk** [comment]
Eza used 2.x IIRC, so you might try to find some way to double check that you're using the latest nerd fonts, exa should not work with 3.x (I think)

**Comment by TallonRain** [comment]
Thanks for the input. I removed the fonts I had installed and grabbed a fresh copy to be certain it was the latest. It looks like that resolved the issue. Seems my config to update it wasn't working as expected, whoops.
