### ISSUE TITLE
feat:  `LS_ICONS` for icon overrides

### ISSUE THREAD

**Issue by pagerc** [eza-community/eza#909]
This is a continuation of the unaddressed exa issue: https://github.com/ogham/exa/issues/559

`LS_ICONS` would make a good corollary to `LS_COLORS` for overriding eza's internal file extension to icon mappings.
Example derived from (https://github.com/ogham/exa/issues/559#issuecomment-517953531):
```
LS_ICONS="*.rb=e21e:*.vim=e62b:*.sh=f292:"
```

**Comment by cafkafk** [comment]
We'd love to see a PR for this if anyone has time :D

**Comment by gierens** [comment]
Since I was just in that part of the code a couple days ago I thought I give it a shot, see the linked PR draft :D

**Comment by gierens** [comment]
I ported my draft from #909 to #840 ... so overriding icons will be a feature of the config file once that is merged.

**Comment by fgclue** [comment]
if this gets added i'm going to finally switch that folder icon with the better one
