### ISSUE TITLE
bug: panic for custom time style in long output

### ISSUE THREAD

**Issue by taminob** [eza-community/eza#912]
I'm not entirely sure if this is actually a bug since I was not able to reproduce it, but I noticed a panic while resolving merge conflicts in the test outputs.
Specifically, in `tests/gen/long_time_style_custom_non_recent_empty_nix.stderr`, `tests/gen/long_time_style_custom_non_recent_none_nix.stderr` and `tests/gen/long_time_style_custom_recent_empty_nix.stderr`, the following panic message appears:

```
thread 'main' panicked at 'Custom timestamp format for recent files is empty, please supply a chrono format string at the second line.', src/options/view.rs:361:25
```

Since a user program should in my opinion never cause a panic, I'd consider this a bug.
The test outputs are checked in the current `main` (e.g. [see here](https://github.com/eza-community/eza/blob/b9dfd61723d0b1e184954eeab93c1087cdf96ed8/tests/gen/long_time_style_custom_recent_empty_nix.stderr#L1)) and the tests pass, thus I guess the panic has to occur somehow.

**Comment by MartinFillon** [comment]
Yes this is intended tho it will be fixed in #787
