### ISSUE TITLE
bug: setting eza_icons_auto does not work

### ISSUE THREAD

**Issue by AngeloThys** [eza-community/eza#917]
# Context

I was trying to get path tab complete to work with `eza --icons`, I then found the environment variable EZA_ICONS_AUTO and tried setting it so I would no longer have to specify the --icons flag.

# Info

- eza version: v0.18.9 [+git]
- command line expression used: eza
- OS: arch
- terminal: kitty

# Issue

After setting EZA_ICONS_AUTO in config.fish:

```fish
set EZA_ICONS_AUTO
```

I closed tmux and fish so the config would get sourced again.

I then tried to run `eza`  to not see any icons.

# Attempts

I tried the following settings:

```fish
set EZA_ICONS_AUTO 
set EZA_ICONS_AUTO 1
set EZA_ICONS_AUTO yes
set EZA_ICONS_AUTO auto
set EZA_ICONS_AUTO always
set eza_icons_auto
set eza_icons_auto 1
set eza_icons_auto always
```

Nothing worked.

**Comment by gierens** [comment]
I don't really know much about fish so I could be mistaken, but don't you have to do `set -x` for it to get exported to child processes:

![Screenshot from 2024-04-04 20-52-10](https://github.com/eza-community/eza/assets/49617392/f54ec629-24ed-4576-b9d4-ccdff33641eb)

**Comment by AngeloThys** [comment]
@gierens You're absolutely right, I was confusing scoping rules with exporting rules, where if scope is not defined, it is set to global by default, however when export rules aren't defined, it's set to not export...

My bad, and thank you!
