### ISSUE TITLE
Indicate folder state with icon

### ISSUE THREAD

**Issue by sbatial** [eza-community/eza#92]
The default folder icon is a closed one.
It would be nice to have an indication for folders that are recursed into/contain files.

See discussion on #46 for further information.

**Comment by PThorpe92** [comment]
Ok what are the thoughts on empty folder vs regular folder? 

Does open indicate that it has files in it? 
Personally I think the outlined glyph of an open folder is more indicative of being empty...
![emptyfolders](https://github.com/eza-community/eza/assets/121899304/8e586efa-7f6e-467a-af7b-fd4b811db0fa)


Also: just realized that I just implemented that (well it wasn't that much work) in my exa directory...
:man_facepalming:

**Comment by sbatial** [comment]
> Personally I think the outlined glyph of an open folder is more indicative of being empty...

Agreed.
I like the first case as well.

> Would you like the PR as a draft?

Sure. That'd be great. :heart:

**Comment by cafkafk** [comment]
This is solved in #137 and will be merged shortly
