### ISSUE TITLE
bug: -X/--dereference was broken and no longer working for filenames

### ISSUE THREAD

**Issue by Vosjedev** [eza-community/eza#932]
Hi!

I found some really inconsystem behaviour when listing symlinks. 
```
$ [[ -L .steampath ]] && echo true
true

$ eza .steampath
.steampath

$ echo "$(eza .steampath)"
.steampath -> /home/vosje/.steam/sdk32/steam

$ echo "$(eza --dereference .steampath)"
.steampath -> /home/vosje/.steam/sdk32/steam

$ echo "$(eza -l --dereference .steampath)"
---------- - - - .steampath -> /home/vosje/.steam/sdk32/steam

$ echo "$(eza -1 --dereference .steampath)"
.steampath -> /home/vosje/.steam/sdk32/steam

$ echo "$(eza -G --dereference .steampath)"
.steampath -> /home/vosje/.steam/sdk32/steam
```

It seems like eza does not care at all about the `-X`/`--dereference` option when output is redirected, does not matter what the mode is. It also does not care about `-X` when in one of the listing modes, or in tree mode. In grid mode it does not list symlink targets at all, but I do understand it doing not it there. But when forced in grid mode with `-GX` it does give a link target, which grid mode did not do before.

In case this is intended behaviour, why is the `-X` option there? Because then it would serve no purpose as far as I know.
*later addition: it seems like -X does more than remove the target, or rather, it does something different than removing the target listing. So how would I then remove the `-> target` part? On `ls` that is `--dereference`.*

I am using `eza` version `v0.18.9 [+git]` (from the AUR). I am running arch linux.

So what I would like to see fixed, is the `-X` option accually getting respected. It seems to do nothing: it is not respected in list, long or tree modes, in grid mode there is no target listed in the first place, and when output is redirected it does not do anything at all.

**Comment by MartinFillon** [comment]
This needs to be tested thoroughly, but I think you got a point here.

**Comment by Vosjedev** [comment]
> This needs to be tested thoroughly
If I can help with anything, just let me know. Just note I have never writen any rust, but I can do testing.

**Comment by MartinFillon** [comment]
> If I can help with anything, just let me know. Just note I have never writen any rust, but I can do testing.

test exemples like a directory or at least files tests so that i could narrow down your problems

**Comment by Vosjedev** [comment]
[![asciicast](https://asciinema.org/a/NxvupCEgBjRgV5IkUhY0SCpaS.svg)](https://asciinema.org/a/NxvupCEgBjRgV5IkUhY0SCpaS)

<details>
<summary>Commands (expand)</Summary>

```bash
# make files
touch file1
mkdir directory

eza

# make symlinks
ln -s file1 symlink_to_file1
ln -s file2 symlink_to_file2 # file2 does not exists; orphaned symlink
ln -s directory symlink_to_directory

eza

# correct behaviour
eza -G symlink_* # should not give link targets
eza -l symlink_* # should give link targets

# incorrect behaviour
eza -l -X symlink_* # should not give link targets
eza -1 -X symlink_* # should not give link targets

# correct behaviour (output redirected)
echo "$(eza -l symlink_*)" # list; should give link targets
echo "$(eza -1 symlink_*)" # list; should give link targets

# incorrect behaviour (output redirected)
echo "$(eza -G symlink_*)" # grouped display, should not give link targets
echo "$(eza -l -X symlink_*)" # -X given, should not give link targets
echo "$(eza -1 -X symlink_*)" # -X given, should not give link targets
```

</details>

<details>
<summary>Terminal session from cast (expand)</summary>

```
> # make files
touch file1
mkdir directory
> eza
directory  file1
> # make symlinks
ln -s file1 symlink_to_file1
ln -s file2 symlink_to_file2 # file2 does not exists; orphaned symlink
ln -s directory symlink_to_directory
> eza
directory  file1  symlink_to_directory  symlink_to_file1  symlink_to_file2
> # correct behaviour
> eza -G symlink_* # should not give link targets
symlink_to_file1  symlink_to_file2

symlink_to_directory:
> eza -l symlink_* # should give link targets
lrwxrwxrwx - vosje 17 Apr 20:17 symlink_to_file1 -> file1
lrwxrwxrwx - vosje 17 Apr 20:17 symlink_to_file2 -> file2

symlink_to_directory:
> # incorrect behaviour
> eza -l -X symlink_* # should not give link targets
lrw-r--r-- 0 vosje 17 Apr 20:17 symlink_to_file1 -> file1
---------- - -     -            symlink_to_file2 -> file2

symlink_to_directory:
> # this gives the targets: symlink_to_file1 -> file1
> eza -1 -X symlink_* # should not give link targets
symlink_to_file1 -> file1
symlink_to_file2 -> file2

symlink_to_directory:
> # that one as well
> # correct behaviour (output redirected)
> echo "$(eza -l symlink_*)" # list; should give link targets
lrwxrwxrwx - vosje 17 Apr 20:17 symlink_to_file1 -> file1
lrwxrwxrwx - vosje 17 Apr 20:17 symlink_to_file2 -> file2

symlink_to_directory:
> echo "$(eza -1 symlink_*)" # list; should give link targets
symlink_to_file1 -> file1
symlink_to_file2 -> file2

symlink_to_directory:
> # incorrect behaviour (output redirected)
> # nothing here should show link targets: grouped should not, list and other list should not because of -X
> echo "$(eza -G symlink_*)" # grouped display, should not give link targets
symlink_to_file1 -> file1
symlink_to_file2 -> file2

symlink_to_directory:
> echo "$(eza -l -X symlink_*)" # -X given, should not give link targets
lrw-r--r-- 0 vosje 17 Apr 20:17 symlink_to_file1 -> file1
---------- - -     -            symlink_to_file2 -> file2

symlink_to_directory:
> echo "$(eza -1 -X symlink_*)" # -X given, should not give link targets
symlink_to_file1 -> file1
symlink_to_file2 -> file2

symlink_to_directory:
> # however all do. Grouped display even shows in list mode instead (the one without info)
```

</details>

Sorry if this is not clear, if I need to clarify anything I did here, please ask.

**Comment by MartinFillon** [comment]
Thanks this seems perfect gonna take a deep dive when I have a bit of time

**Comment by Vosjedev** [comment]
That indeed fixed everything, thank you very much!

**Comment by wlritchi** [comment]
I frequently use `eza -labX`, and I'm looking to answer both "where do symlinks point?" and "what are the modes and sizes of their targets?". For this use case, the old behaviour worked perfectly, but the new logic doesn't let me view both pieces of information at once.

That said, I completely agree that it's weird for `eza | cat` to list the target when `eza` doesn't. And `ls | cat` doesn't list the target either, so it's not a compat thing.

I'm not sure if my expectation of what `-X` is for lines up with @Vosjedev's. To me, it's about what to show for the stat result, and it shouldn't have any interplay with the file name at all. I think the idea that it would suppress printing the link target is a red herring - the real problem is the fact that the target's being printed in the first place, when it probably shouldn't be.
