### ISSUE TITLE
bug: does not follows `.gitignore`

### ISSUE THREAD

**Issue by dalisoft** [eza-community/eza#938]
If eza does something unexpected, or its output looks wrong, or it displays an error on the screen, or if it outright crashes, then please include the following information in your report:

- The version of eza being used (`eza --version`): `v0.18.10 [+git]`
- The command-line arguments you are using: `ls -hlaST --git --git-repos --octal-permissions --time-style=long-iso`
- Your operating system and hardware platform: `macOS 14.4.1`

If it’s a crash, please include the full text of the crash that gets printed to the screen. If you’re seeing unexpected behaviour, a screenshot of the issue will help a lot.

<img width="1440" alt="image" src="https://github.com/eza-community/eza/assets/3511344/fb95e599-985a-4a7a-ade9-e3d76170b26b">

---

**Comment by daviessm** [comment]
You need to add the `--git-ignore` parameter as shown in the help:

`  --git-ignore               ignore files mentioned in '.gitignore'`
