### ISSUE TITLE
feat:  SELinux support

### ISSUE THREAD

**Issue by dylanmtaylor** [eza-community/eza#952]
ls -Z and eza -Z have very different results produced

**Comment by cafkafk** [comment]
could you describe in more detail what the differences are and how this affects your usage?

**Comment by dylanmtaylor** [comment]
ls -Z:
![image](https://github.com/eza-community/eza/assets/277927/8b7181cb-faee-483c-9a38-abe70071a82f)

eza -Z:
![image](https://github.com/eza-community/eza/assets/277927/20cba211-e72d-4893-845e-29adace5d3db)

**Comment by cafkafk** [comment]
what does this look like with the -l flag?

**Comment by dylanmtaylor** [comment]
ls -l
![image](https://github.com/eza-community/eza/assets/277927/28f1db9c-5b68-4abc-80f5-e67b53155757)

eza -l
![image](https://github.com/eza-community/eza/assets/277927/84eb4560-f96a-4f08-a9a5-f712f52aa40b)

You can test on a Fedora Live ISO which has SELinux by default.

**Comment by MartinFillon** [comment]
Hey, as per right now, `-Z` or security contextm is keeped behind two things, first the `-l` flag, and secondly xattr, they need to be enabled, they are currenty only supported on target oses:
- `linux`
- `netbsd`
- `macos`
- `freebsd`

if SELinux is a different os than those then this can be the reason why its not working. As I dont have the ability to run a SELinux os . Feel free to test and maybe debug the variable to see if its enabled in a rust basic project. [code](https://github.com/eza-community/eza/blob/main/src/fs/feature/xattr.rs) the `ENABLED` const is here the reason.

**Comment by dylanmtaylor** [comment]
> Hey, as per right now, `-Z` or security contextm is keeped behind two things, first the `-l` flag, and secondly xattr, they need to be enabled, they are currenty only supported on target oses:
> 
>     * `linux`
> 
>     * `netbsd`
> 
>     * `macos`
> 
>     * `freebsd`
> 
> 
> if SELinux is a different os than those then this can be the reason why its not working. As I dont have the ability to run a SELinux os . Feel free to test and maybe debug the variable to see if its enabled in a rust basic project. [code](https://github.com/eza-community/eza/blob/main/src/fs/feature/xattr.rs) the `ENABLED` const is here the reason.

SELinux is not a different OS than Linux.

**Comment by MartinFillon** [comment]
> SELinux is not a different OS than Linux.

Ok then i think you not having the same output is due to us gatekeeping it behind `-l`

**Comment by shdwchn10** [comment]
I use SELinux-enabled Linux system (Fedora Silverblue) and can't see SELinux labels

```
allthetools on  main 
❯ uname -a           
Linux localhost 6.9.4-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 12 13:33:34 UTC 2024 x86_64 GNU/Linux

allthetools on  main 
❯ eza -l             
drwxr-xr-x@    - shdwchn10 11 Jun 12:03 chezmoi
drwxr-xr-x@    - shdwchn10  8 Jun 12:33 eza
drwxr-xr-x@    - shdwchn10 17 Jun 23:24 fzf
drwxr-xr-x@    - shdwchn10  8 Jun 14:14 gum
.rw-r--r--@  11k shdwchn10  8 Jun 15:39 LICENSE
drwxr-xr-x@    - shdwchn10 11 Jun 11:39 nu
drwxr-xr-x@    - shdwchn10 18 Jun 07:38 pueue
.rw-r--r--@ 1.8k shdwchn10 18 Jun 09:40 README.md
drwxr-xr-x@    - shdwchn10 18 Jun 09:17 solo2
drwxr-xr-x@    - shdwchn10  8 Jun 14:28 starship
drwxr-xr-x@    - shdwchn10 18 Jun 07:16 topgrade
drwxr-xr-x@    - shdwchn10 17 Jun 23:24 zoxide

allthetools on  main 
❯ sestatus           
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

allthetools on  main 
❯ cat /etc/os-release
NAME="Fedora Linux"
VERSION="40.20240618.0 (Silverblue)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40.20240618.0 (Silverblue)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://silverblue.fedoraproject.org"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://github.com/fedora-silverblue/issue-tracker/issues"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='40.20240618.0'
```

**Comment by cafkafk** [comment]
Okay, closing as solved :3
