### ISSUE TITLE
bug: eza installation fails - winget

### ISSUE THREAD

**Issue by scottmckendry** [eza-community/eza#953]
Trying to install the latest version of eza via winget on Windows 23H3 and I get the following error:
```
An unexpected error occurred while executing the command:
[YAML:Policy] unsupported control character [line 1; col 14]
0x8a150004 : Opening manifest failed
```
![image](https://github.com/eza-community/eza/assets/39483124/7c244cb5-0c93-4d23-a28b-6bf65bfed164)

I've also tried 0.18.11 & 0.18.10 with the same result.

**Comment by cafkafk** [comment]
I'm personally not able to assist much when it comes to winget/windows (I don't even have a windows computer!)

You might have more luck asking upstream in winget?

**Comment by michaelfsp** [comment]
I was getting the same error as @scottmckendry. It seems like winget takes issue with the double quotes on the Description section of eza-community.eza.locale.en-US.yaml (line 15; col 14)
Reformatting the YAML files with yq (via conform.nvim in neovim) fixed the issue for me. I've sent a pull request for the fix.

**Comment by scottmckendry** [comment]
@michaelfsp you're a ⭐ 
Thankyou!
