### ISSUE TITLE
bug: archlinux installation eza error

### ISSUE THREAD

**Issue by wengyk** [eza-community/eza#962]
I'm using archLinux, I've been using eza normally before, and when I upgraded my system today, I got the following error message：

warning: cannot resolve "zlib.so", a dependency of "eza"
:: The following package cannot be upgraded due to unresolvable dependencies: eza

Then the eza installation fails.

**Comment by spaceCabbage** [comment]
me too

**Comment by cafkafk** [comment]
It's being tracked upstream https://gitlab.archlinux.org/archlinux/packaging/packages/eza/-/issues/1

**Comment by spaceCabbage** [comment]
any fix/workaround yet?

**Comment by aloispichler** [comment]
me too.

**Comment by cafkafk** [comment]
seems like it's solved upstream, closing.
