### ISSUE TITLE
feat: In tree view, the branch child contents should line up with the parent's first symbol

### ISSUE THREAD

**Issue by acid-bong** [eza-community/eza#984]
Expected behaviour: like `tree` has it -- the vertical bar descends right from the first character
```
.config/nixos/pkgs
├── default.nix
├── desktop-scripts
│   ├── default.nix
│   ├── sqrt.sh
│   └── tp-toggle.sh
├── lilex-nerdfont
│   └── default.nix
└── nf
    └── default.nix

4 directories, 6 files
```
Actual behaviour: the vertical bar starts one column before the word start (the same with icons and without)
```
.config/nixos/pkgs
├── default.nix
├── desktop-scripts
│  ├── default.nix
│  ├── sqrt.sh
│  └── tp-toggle.sh
├── lilex-nerdfont
│  └── default.nix
└── nf
   └── default.nix
```
Proposal: make it look like in the tree output

**Comment by bew** [comment]
Hello!
I noticed this today as well, and made a PR #1193 to fix it 🙃

**Comment by acid-bong** [comment]
Just built, it looks exactly like `tree`
