### ISSUE TITLE
feat: dynamic navigation of tree

### ISSUE THREAD

**Issue by patata3000** [eza-community/eza#992]
Tree mode is great. I wish I could go around the tree with a pager and see the context of the current directories of where I'm looking in the tree.

Maybe it's out of the scope of eza but still one guy can dream.

**Comment by cafkafk** [comment]
I think it may be a bit out of scope :D That said, I'm sure someone could create some script to do this, but then again, you may be looking for a file browser, I recommend https://github.com/jarun/nnn
